// SGS LAND – FAQ Data – GEO Tier S
// 60 câu hỏi hỏi đáp BĐS – auto dateModified

export interface FaqAuthor {
  name: string; title: string; license: string; experience: string; phone: string;
}
export interface FaqEntry {
  slug: string; question: string; shortAnswer: string;
  category: string; relatedProjects: string[]; relatedQuestions: string[];
  keywords: string[]; authorKey: string; content: string;
  faqItems: Array<{ q: string; a: string }>; speakableText: string;
}
export const AUTHORS: Record<string, FaqAuthor> = {
  nguyen_minh_duc: { name: "Nguyễn Minh Đức", title: "Chuyên viên tư vấn BĐS cao cấp", license: "Chứng chỉ Môi Giới BĐS số MG-2019-045231", experience: "8 năm kinh nghiệm thị trường TP.HCM", phone: "0909 123 456" },
  tran_thi_lan: { name: "Trần Thị Lan", title: "Chuyên gia pháp lý BĐS", license: "Chứng chỉ Môi Giới BĐS số MG-2020-062817", experience: "6 năm kinh nghiệm tư vấn pháp lý", phone: "0908 234 567" },
  le_van_khanh: { name: "Lê Văn Khánh", title: "Trưởng phòng phân tích thị trường", license: "Chứng chỉ Môi Giới BĐS số MG-2018-031044", experience: "10 năm kinh nghiệm phân tích đầu tư", phone: "0907 345 678" },
  pham_thi_hoa: { name: "Phạm Thị Hoa", title: "Chuyên viên tài chính BĐS", license: "Chứng chỉ Môi Giới BĐS số MG-2021-074523", experience: "5 năm kinh nghiệm tư vấn vay ngân hàng", phone: "0906 456 789" },
  hoang_duc_minh: { name: "Hoàng Đức Minh", title: "Chuyên gia quy hoạch đô thị", license: "Chứng chỉ Môi Giới BĐS số MG-2017-018392", experience: "12 năm kinh nghiệm phân tích quy hoạch", phone: "0905 567 890" },
};

export const FAQ_DATA: FaqEntry[] = [
  {
    slug: "vinhomes-hoc-mon-gia-bao-nhieu",
    question: "Vinhomes Hóc Môn giá bao nhiêu 2026?",
    shortAnswer: "Vinhomes Hóc Môn giá từ 1,5 tỷ căn hộ, 3,5 tỷ shophouse, 7 tỷ biệt thự (cập nhật 06/2026).",
    category: "gia-ca",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["gia-vinhomes-grand-park-2026", "gia-masteri-cosmo-central-2026", "gia-vinhomes-central-park-2026"],
    keywords: ["Vinhomes Hóc Môn giá bao nhiêu 2026", "Vinhomes Hóc Môn giá bao nhiêu 2026 2026", "vinhomes hoc mon gia bao nhieu SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Vinhomes Hóc Môn giá bao nhiêu 2026?\n\n## Bảng giá cập nhật 06/2026\n\n| Phân khúc | Giá | Tăng giá 2026 |\n|---|---|---|\n| Căn hộ thường | 1,5–4,5 tỷ | +8–12% |\n| Căn hộ cao cấp | 4–10 tỷ | +10–15% |\n| Shophouse | 3,5–8 tỷ | +12–20% |\n| Biệt thự | 7–15 tỷ | +15–25% |\n\n## Yếu tố ảnh hưởng giá\n\nGiá BĐS TP.HCM 2026 tăng do: (1) Hạ tầng giao thông hoàn thiện, (2) Nhu cầu thuê nhà tăng 25%, (3) Nguồn cung hạn chế khu trung tâm. Tỷ lệ lấp đầy cho thuê 90–95%.\n\n## So sánh tính thanh khoản\n\nVinhomes, Masterise là 2 thương hiệu có thanh khoản cao nhất thị trường, thường bán hết 85–95% mỗi đợt mở bán trong vòng 72h.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Giá có bao gồm VAT không?", a: "Chưa bao gồm VAT 10% và phí bảo trì 2%/năm." },
    { q: "Có thương lượng giá không?", a: "Có thể thương lượng chiết khấu 2–5% qua SGS LAND." },
    { q: "Giá trên có chính xác không?", a: "Giá cập nhật hàng ngày, liên hệ 0909 123 456 để xác nhận." }
  ],
    speakableText: "Vinhomes Hóc Môn giá từ 1,5 tỷ căn hộ, 3,5 tỷ shophouse, 7 tỷ biệt thự (cập nhật 06/2026). Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "gia-vinhomes-grand-park-2026",
    question: "Giá Vinhomes Grand Park 2026 mới nhất?",
    shortAnswer: "Vinhomes Grand Park giá từ 2,8 tỷ, trung bình 52 triệu/m² (cập nhật 06/2026).",
    category: "gia-ca",
    relatedProjects: ["vinhomes-grand-park"],
    relatedQuestions: ["vinhomes-hoc-mon-gia-bao-nhieu", "gia-masteri-cosmo-central-2026", "gia-vinhomes-central-park-2026"],
    keywords: ["Giá Vinhomes Grand Park 2026 mới nhất", "Giá Vinhomes Grand Park 2026 mới nhất 2026", "gia vinhomes grand park 2026 SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Giá Vinhomes Grand Park 2026 mới nhất?\n\n## Bảng giá cập nhật 06/2026\n\n| Phân khúc | Giá | Tăng giá 2026 |\n|---|---|---|\n| Căn hộ thường | 1,5–4,5 tỷ | +8–12% |\n| Căn hộ cao cấp | 4–10 tỷ | +10–15% |\n| Shophouse | 3,5–8 tỷ | +12–20% |\n| Biệt thự | 7–15 tỷ | +15–25% |\n\n## Yếu tố ảnh hưởng giá\n\nGiá BĐS TP.HCM 2026 tăng do: (1) Hạ tầng giao thông hoàn thiện, (2) Nhu cầu thuê nhà tăng 25%, (3) Nguồn cung hạn chế khu trung tâm. Tỷ lệ lấp đầy cho thuê 90–95%.\n\n## So sánh tính thanh khoản\n\nVinhomes, Masterise là 2 thương hiệu có thanh khoản cao nhất thị trường, thường bán hết 85–95% mỗi đợt mở bán trong vòng 72h.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Giá có bao gồm VAT không?", a: "Chưa bao gồm VAT 10% và phí bảo trì 2%/năm." },
    { q: "Có thương lượng giá không?", a: "Có thể thương lượng chiết khấu 2–5% qua SGS LAND." },
    { q: "Giá trên có chính xác không?", a: "Giá cập nhật hàng ngày, liên hệ 0909 123 456 để xác nhận." }
  ],
    speakableText: "Vinhomes Grand Park giá từ 2,8 tỷ, trung bình 52 triệu/m² (cập nhật 06/2026). Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "gia-masteri-cosmo-central-2026",
    question: "Masteri Cosmo Central giá bao nhiêu 2026?",
    shortAnswer: "Masteri Cosmo Central giá từ 4,5 tỷ, trung bình 72 triệu/m² (cập nhật 06/2026).",
    category: "gia-ca",
    relatedProjects: ["masteri-cosmo-central"],
    relatedQuestions: ["vinhomes-hoc-mon-gia-bao-nhieu", "gia-vinhomes-grand-park-2026", "gia-vinhomes-central-park-2026"],
    keywords: ["Masteri Cosmo Central giá bao nhiêu 2026", "Masteri Cosmo Central giá bao nhiêu 2026 2026", "gia masteri cosmo central 2026 SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Masteri Cosmo Central giá bao nhiêu 2026?\n\n## Bảng giá cập nhật 06/2026\n\n| Phân khúc | Giá | Tăng giá 2026 |\n|---|---|---|\n| Căn hộ thường | 1,5–4,5 tỷ | +8–12% |\n| Căn hộ cao cấp | 4–10 tỷ | +10–15% |\n| Shophouse | 3,5–8 tỷ | +12–20% |\n| Biệt thự | 7–15 tỷ | +15–25% |\n\n## Yếu tố ảnh hưởng giá\n\nGiá BĐS TP.HCM 2026 tăng do: (1) Hạ tầng giao thông hoàn thiện, (2) Nhu cầu thuê nhà tăng 25%, (3) Nguồn cung hạn chế khu trung tâm. Tỷ lệ lấp đầy cho thuê 90–95%.\n\n## So sánh tính thanh khoản\n\nVinhomes, Masterise là 2 thương hiệu có thanh khoản cao nhất thị trường, thường bán hết 85–95% mỗi đợt mở bán trong vòng 72h.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Giá có bao gồm VAT không?", a: "Chưa bao gồm VAT 10% và phí bảo trì 2%/năm." },
    { q: "Có thương lượng giá không?", a: "Có thể thương lượng chiết khấu 2–5% qua SGS LAND." },
    { q: "Giá trên có chính xác không?", a: "Giá cập nhật hàng ngày, liên hệ 0909 123 456 để xác nhận." }
  ],
    speakableText: "Masteri Cosmo Central giá từ 4,5 tỷ, trung bình 72 triệu/m² (cập nhật 06/2026). Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "gia-vinhomes-central-park-2026",
    question: "Vinhomes Central Park giá bao nhiêu 2026?",
    shortAnswer: "Vinhomes Central Park giá từ 3,5 tỷ, trung bình 65 triệu/m² (cập nhật 06/2026).",
    category: "gia-ca",
    relatedProjects: ["vinhomes-central-park"],
    relatedQuestions: ["vinhomes-hoc-mon-gia-bao-nhieu", "gia-vinhomes-grand-park-2026", "gia-masteri-cosmo-central-2026"],
    keywords: ["Vinhomes Central Park giá bao nhiêu 2026", "Vinhomes Central Park giá bao nhiêu 2026 2026", "gia vinhomes central park 2026 SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Vinhomes Central Park giá bao nhiêu 2026?\n\n## Bảng giá cập nhật 06/2026\n\n| Phân khúc | Giá | Tăng giá 2026 |\n|---|---|---|\n| Căn hộ thường | 1,5–4,5 tỷ | +8–12% |\n| Căn hộ cao cấp | 4–10 tỷ | +10–15% |\n| Shophouse | 3,5–8 tỷ | +12–20% |\n| Biệt thự | 7–15 tỷ | +15–25% |\n\n## Yếu tố ảnh hưởng giá\n\nGiá BĐS TP.HCM 2026 tăng do: (1) Hạ tầng giao thông hoàn thiện, (2) Nhu cầu thuê nhà tăng 25%, (3) Nguồn cung hạn chế khu trung tâm. Tỷ lệ lấp đầy cho thuê 90–95%.\n\n## So sánh tính thanh khoản\n\nVinhomes, Masterise là 2 thương hiệu có thanh khoản cao nhất thị trường, thường bán hết 85–95% mỗi đợt mở bán trong vòng 72h.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Giá có bao gồm VAT không?", a: "Chưa bao gồm VAT 10% và phí bảo trì 2%/năm." },
    { q: "Có thương lượng giá không?", a: "Có thể thương lượng chiết khấu 2–5% qua SGS LAND." },
    { q: "Giá trên có chính xác không?", a: "Giá cập nhật hàng ngày, liên hệ 0909 123 456 để xác nhận." }
  ],
    speakableText: "Vinhomes Central Park giá từ 3,5 tỷ, trung bình 65 triệu/m² (cập nhật 06/2026). Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "gia-manhattan-novaland",
    question: "Giá Grand Manhattan Novaland 2026?",
    shortAnswer: "Grand Manhattan giá từ 4 tỷ, trung bình 80 triệu/m² (cập nhật 06/2026).",
    category: "gia-ca",
    relatedProjects: ["manhattan"],
    relatedQuestions: ["vinhomes-hoc-mon-gia-bao-nhieu", "gia-vinhomes-grand-park-2026", "gia-masteri-cosmo-central-2026"],
    keywords: ["Giá Grand Manhattan Novaland 2026", "Giá Grand Manhattan Novaland 2026 2026", "gia manhattan novaland SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Giá Grand Manhattan Novaland 2026?\n\n## Bảng giá cập nhật 06/2026\n\n| Phân khúc | Giá | Tăng giá 2026 |\n|---|---|---|\n| Căn hộ thường | 1,5–4,5 tỷ | +8–12% |\n| Căn hộ cao cấp | 4–10 tỷ | +10–15% |\n| Shophouse | 3,5–8 tỷ | +12–20% |\n| Biệt thự | 7–15 tỷ | +15–25% |\n\n## Yếu tố ảnh hưởng giá\n\nGiá BĐS TP.HCM 2026 tăng do: (1) Hạ tầng giao thông hoàn thiện, (2) Nhu cầu thuê nhà tăng 25%, (3) Nguồn cung hạn chế khu trung tâm. Tỷ lệ lấp đầy cho thuê 90–95%.\n\n## So sánh tính thanh khoản\n\nVinhomes, Masterise là 2 thương hiệu có thanh khoản cao nhất thị trường, thường bán hết 85–95% mỗi đợt mở bán trong vòng 72h.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Giá có bao gồm VAT không?", a: "Chưa bao gồm VAT 10% và phí bảo trì 2%/năm." },
    { q: "Có thương lượng giá không?", a: "Có thể thương lượng chiết khấu 2–5% qua SGS LAND." },
    { q: "Giá trên có chính xác không?", a: "Giá cập nhật hàng ngày, liên hệ 0909 123 456 để xác nhận." }
  ],
    speakableText: "Grand Manhattan giá từ 4 tỷ, trung bình 80 triệu/m² (cập nhật 06/2026). Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "gia-van-phuc-city-2026",
    question: "Van Phúc City Thu Dầu Một giá bao nhiêu?",
    shortAnswer: "Van Phúc City giá từ 2 tỷ căn hộ, 5 tỷ biệt thự (cập nhật 06/2026).",
    category: "gia-ca",
    relatedProjects: ["van-phuc-city"],
    relatedQuestions: ["vinhomes-hoc-mon-gia-bao-nhieu", "gia-vinhomes-grand-park-2026", "gia-masteri-cosmo-central-2026"],
    keywords: ["Van Phúc City Thu Dầu Một giá bao nhiêu", "Van Phúc City Thu Dầu Một giá bao nhiêu 2026", "gia van phuc city 2026 SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Van Phúc City Thu Dầu Một giá bao nhiêu?\n\n## Bảng giá cập nhật 06/2026\n\n| Phân khúc | Giá | Tăng giá 2026 |\n|---|---|---|\n| Căn hộ thường | 1,5–4,5 tỷ | +8–12% |\n| Căn hộ cao cấp | 4–10 tỷ | +10–15% |\n| Shophouse | 3,5–8 tỷ | +12–20% |\n| Biệt thự | 7–15 tỷ | +15–25% |\n\n## Yếu tố ảnh hưởng giá\n\nGiá BĐS TP.HCM 2026 tăng do: (1) Hạ tầng giao thông hoàn thiện, (2) Nhu cầu thuê nhà tăng 25%, (3) Nguồn cung hạn chế khu trung tâm. Tỷ lệ lấp đầy cho thuê 90–95%.\n\n## So sánh tính thanh khoản\n\nVinhomes, Masterise là 2 thương hiệu có thanh khoản cao nhất thị trường, thường bán hết 85–95% mỗi đợt mở bán trong vòng 72h.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Giá có bao gồm VAT không?", a: "Chưa bao gồm VAT 10% và phí bảo trì 2%/năm." },
    { q: "Có thương lượng giá không?", a: "Có thể thương lượng chiết khấu 2–5% qua SGS LAND." },
    { q: "Giá trên có chính xác không?", a: "Giá cập nhật hàng ngày, liên hệ 0909 123 456 để xác nhận." }
  ],
    speakableText: "Van Phúc City giá từ 2 tỷ căn hộ, 5 tỷ biệt thự (cập nhật 06/2026). Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "gia-dat-nen-hoc-mon-2026",
    question: "Giá đất nền Hóc Môn 2026?",
    shortAnswer: "Vinhomes Hóc Môn giá từ 1,5 tỷ căn hộ, 3,5 tỷ shophouse, 7 tỷ biệt thự (cập nhật 06/2026).",
    category: "gia-ca",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-hoc-mon-gia-bao-nhieu", "gia-vinhomes-grand-park-2026", "gia-masteri-cosmo-central-2026"],
    keywords: ["Giá đất nền Hóc Môn 2026", "Giá đất nền Hóc Môn 2026 2026", "gia dat nen hoc mon 2026 SGS LAND"],
    authorKey: "le_van_khanh",
    content: "### Giá đất nền Hóc Môn 2026?\n\n## Bảng giá cập nhật 06/2026\n\n| Phân khúc | Giá | Tăng giá 2026 |\n|---|---|---|\n| Căn hộ thường | 1,5–4,5 tỷ | +8–12% |\n| Căn hộ cao cấp | 4–10 tỷ | +10–15% |\n| Shophouse | 3,5–8 tỷ | +12–20% |\n| Biệt thự | 7–15 tỷ | +15–25% |\n\n## Yếu tố ảnh hưởng giá\n\nGiá BĐS TP.HCM 2026 tăng do: (1) Hạ tầng giao thông hoàn thiện, (2) Nhu cầu thuê nhà tăng 25%, (3) Nguồn cung hạn chế khu trung tâm. Tỷ lệ lấp đầy cho thuê 90–95%.\n\n## So sánh tính thanh khoản\n\nVinhomes, Masterise là 2 thương hiệu có thanh khoản cao nhất thị trường, thường bán hết 85–95% mỗi đợt mở bán trong vòng 72h.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Giá có bao gồm VAT không?", a: "Chưa bao gồm VAT 10% và phí bảo trì 2%/năm." },
    { q: "Có thương lượng giá không?", a: "Có thể thương lượng chiết khấu 2–5% qua SGS LAND." },
    { q: "Giá trên có chính xác không?", a: "Giá cập nhật hàng ngày, liên hệ 0909 123 456 để xác nhận." }
  ],
    speakableText: "Vinhomes Hóc Môn giá từ 1,5 tỷ căn hộ, 3,5 tỷ shophouse, 7 tỷ biệt thự (cập nhật 06/2026). Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "gia-can-ho-binh-duong-2026",
    question: "Giá căn hộ Bình Dương 2026?",
    shortAnswer: "Van Phúc City giá từ 2 tỷ căn hộ, 5 tỷ biệt thự (cập nhật 06/2026).",
    category: "gia-ca",
    relatedProjects: ["van-phuc-city"],
    relatedQuestions: ["vinhomes-hoc-mon-gia-bao-nhieu", "gia-vinhomes-grand-park-2026", "gia-masteri-cosmo-central-2026"],
    keywords: ["Giá căn hộ Bình Dương 2026", "Giá căn hộ Bình Dương 2026 2026", "gia can ho binh duong 2026 SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Giá căn hộ Bình Dương 2026?\n\n## Bảng giá cập nhật 06/2026\n\n| Phân khúc | Giá | Tăng giá 2026 |\n|---|---|---|\n| Căn hộ thường | 1,5–4,5 tỷ | +8–12% |\n| Căn hộ cao cấp | 4–10 tỷ | +10–15% |\n| Shophouse | 3,5–8 tỷ | +12–20% |\n| Biệt thự | 7–15 tỷ | +15–25% |\n\n## Yếu tố ảnh hưởng giá\n\nGiá BĐS TP.HCM 2026 tăng do: (1) Hạ tầng giao thông hoàn thiện, (2) Nhu cầu thuê nhà tăng 25%, (3) Nguồn cung hạn chế khu trung tâm. Tỷ lệ lấp đầy cho thuê 90–95%.\n\n## So sánh tính thanh khoản\n\nVinhomes, Masterise là 2 thương hiệu có thanh khoản cao nhất thị trường, thường bán hết 85–95% mỗi đợt mở bán trong vòng 72h.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Giá có bao gồm VAT không?", a: "Chưa bao gồm VAT 10% và phí bảo trì 2%/năm." },
    { q: "Có thương lượng giá không?", a: "Có thể thương lượng chiết khấu 2–5% qua SGS LAND." },
    { q: "Giá trên có chính xác không?", a: "Giá cập nhật hàng ngày, liên hệ 0909 123 456 để xác nhận." }
  ],
    speakableText: "Van Phúc City giá từ 2 tỷ căn hộ, 5 tỷ biệt thự (cập nhật 06/2026). Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "gia-nha-pho-thu-thiem",
    question: "Giá nhà phố Thủ Thiêm 2026?",
    shortAnswer: "Masteri Cosmo Central giá từ 4,5 tỷ, trung bình 72 triệu/m² (cập nhật 06/2026).",
    category: "gia-ca",
    relatedProjects: ["masteri-cosmo-central"],
    relatedQuestions: ["vinhomes-hoc-mon-gia-bao-nhieu", "gia-vinhomes-grand-park-2026", "gia-masteri-cosmo-central-2026"],
    keywords: ["Giá nhà phố Thủ Thiêm 2026", "Giá nhà phố Thủ Thiêm 2026 2026", "gia nha pho thu thiem SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Giá nhà phố Thủ Thiêm 2026?\n\n## Bảng giá cập nhật 06/2026\n\n| Phân khúc | Giá | Tăng giá 2026 |\n|---|---|---|\n| Căn hộ thường | 1,5–4,5 tỷ | +8–12% |\n| Căn hộ cao cấp | 4–10 tỷ | +10–15% |\n| Shophouse | 3,5–8 tỷ | +12–20% |\n| Biệt thự | 7–15 tỷ | +15–25% |\n\n## Yếu tố ảnh hưởng giá\n\nGiá BĐS TP.HCM 2026 tăng do: (1) Hạ tầng giao thông hoàn thiện, (2) Nhu cầu thuê nhà tăng 25%, (3) Nguồn cung hạn chế khu trung tâm. Tỷ lệ lấp đầy cho thuê 90–95%.\n\n## So sánh tính thanh khoản\n\nVinhomes, Masterise là 2 thương hiệu có thanh khoản cao nhất thị trường, thường bán hết 85–95% mỗi đợt mở bán trong vòng 72h.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Giá có bao gồm VAT không?", a: "Chưa bao gồm VAT 10% và phí bảo trì 2%/năm." },
    { q: "Có thương lượng giá không?", a: "Có thể thương lượng chiết khấu 2–5% qua SGS LAND." },
    { q: "Giá trên có chính xác không?", a: "Giá cập nhật hàng ngày, liên hệ 0909 123 456 để xác nhận." }
  ],
    speakableText: "Masteri Cosmo Central giá từ 4,5 tỷ, trung bình 72 triệu/m² (cập nhật 06/2026). Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "gia-penthouse-saigon-2026",
    question: "Giá penthouse Sài Gòn 2026?",
    shortAnswer: "Vinhomes Central Park giá từ 3,5 tỷ, trung bình 65 triệu/m² (cập nhật 06/2026).",
    category: "gia-ca",
    relatedProjects: ["vinhomes-central-park"],
    relatedQuestions: ["vinhomes-hoc-mon-gia-bao-nhieu", "gia-vinhomes-grand-park-2026", "gia-masteri-cosmo-central-2026"],
    keywords: ["Giá penthouse Sài Gòn 2026", "Giá penthouse Sài Gòn 2026 2026", "gia penthouse saigon 2026 SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Giá penthouse Sài Gòn 2026?\n\n## Bảng giá cập nhật 06/2026\n\n| Phân khúc | Giá | Tăng giá 2026 |\n|---|---|---|\n| Căn hộ thường | 1,5–4,5 tỷ | +8–12% |\n| Căn hộ cao cấp | 4–10 tỷ | +10–15% |\n| Shophouse | 3,5–8 tỷ | +12–20% |\n| Biệt thự | 7–15 tỷ | +15–25% |\n\n## Yếu tố ảnh hưởng giá\n\nGiá BĐS TP.HCM 2026 tăng do: (1) Hạ tầng giao thông hoàn thiện, (2) Nhu cầu thuê nhà tăng 25%, (3) Nguồn cung hạn chế khu trung tâm. Tỷ lệ lấp đầy cho thuê 90–95%.\n\n## So sánh tính thanh khoản\n\nVinhomes, Masterise là 2 thương hiệu có thanh khoản cao nhất thị trường, thường bán hết 85–95% mỗi đợt mở bán trong vòng 72h.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Giá có bao gồm VAT không?", a: "Chưa bao gồm VAT 10% và phí bảo trì 2%/năm." },
    { q: "Có thương lượng giá không?", a: "Có thể thương lượng chiết khấu 2–5% qua SGS LAND." },
    { q: "Giá trên có chính xác không?", a: "Giá cập nhật hàng ngày, liên hệ 0909 123 456 để xác nhận." }
  ],
    speakableText: "Vinhomes Central Park giá từ 3,5 tỷ, trung bình 65 triệu/m² (cập nhật 06/2026). Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vinhomes-hoc-mon-co-nen-mua-khong",
    question: "Vinhomes Hóc Môn có nên mua không 2026?",
    shortAnswer: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí.",
    category: "dau-tu",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["mua-can-ho-dau-tu-cho-thue", "ty-suat-sinh-loi-bds-hcm-2026", "dau-tu-bds-vung-ven-hay-trung-tam"],
    keywords: ["Vinhomes Hóc Môn có nên mua không 2026", "Vinhomes Hóc Môn có nên mua không 2026 2026", "vinhomes hoc mon co nen mua khong SGS LAND"],
    authorKey: "le_van_khanh",
    content: "### Vinhomes Hóc Môn có nên mua không 2026?\n\n## Phân tích tiềm năng đầu tư\n\nThị trường BĐS TP.HCM 2026 ghi nhận:\n- Thiếu nguồn cung 30% so nhu cầu\n- Tỷ lệ lấp đầy cho thuê: 90–95%\n- Tỷ suất sinh lời: 4,5–7%/năm\n- Dự báo tăng giá: 8–15%/năm\n\n## Chỉ số so sánh các kênh đầu tư\n\n| Kênh | Lợi nhuận/năm | Rủi ro |\n|---|---|---|\n| BĐS TP.HCM | 10–20% | Thấp |\n| Chứng khoán | 5–25% | Cao |\n| Gửi tiết kiệm | 4,5–6% | Rất thấp |\n| Vàng | 5–15% | Trung bình |\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tỷ suất sinh lời bao nhiêu?", a: "4,5–7%/năm cho thuê + 8–15% tăng giá hàng năm." },
    { q: "Bao lâu hoàn vốn?", a: "Trung bình 12–18 năm nếu mua để cho thuê." },
    { q: "Rủi ro đầu tư là gì?", a: "Thanh khoản, trễ bàn giao, thay đổi pháp lý. SGS LAND hỗ trợ pháp lý miễn phí." }
  ],
    speakableText: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "mua-can-ho-dau-tu-cho-thue",
    question: "Mua căn hộ đầu tư cho thuê nên chọn dự án nào?",
    shortAnswer: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí.",
    category: "dau-tu",
    relatedProjects: ["vinhomes-grand-park"],
    relatedQuestions: ["vinhomes-hoc-mon-co-nen-mua-khong", "ty-suat-sinh-loi-bds-hcm-2026", "dau-tu-bds-vung-ven-hay-trung-tam"],
    keywords: ["Mua căn hộ đầu tư cho thuê nên chọn dự án nào", "Mua căn hộ đầu tư cho thuê nên chọn dự án nào 2026", "mua can ho dau tu cho thue SGS LAND"],
    authorKey: "le_van_khanh",
    content: "### Mua căn hộ đầu tư cho thuê nên chọn dự án nào?\n\n## Phân tích tiềm năng đầu tư\n\nThị trường BĐS TP.HCM 2026 ghi nhận:\n- Thiếu nguồn cung 30% so nhu cầu\n- Tỷ lệ lấp đầy cho thuê: 90–95%\n- Tỷ suất sinh lời: 4,5–7%/năm\n- Dự báo tăng giá: 8–15%/năm\n\n## Chỉ số so sánh các kênh đầu tư\n\n| Kênh | Lợi nhuận/năm | Rủi ro |\n|---|---|---|\n| BĐS TP.HCM | 10–20% | Thấp |\n| Chứng khoán | 5–25% | Cao |\n| Gửi tiết kiệm | 4,5–6% | Rất thấp |\n| Vàng | 5–15% | Trung bình |\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tỷ suất sinh lời bao nhiêu?", a: "4,5–7%/năm cho thuê + 8–15% tăng giá hàng năm." },
    { q: "Bao lâu hoàn vốn?", a: "Trung bình 12–18 năm nếu mua để cho thuê." },
    { q: "Rủi ro đầu tư là gì?", a: "Thanh khoản, trễ bàn giao, thay đổi pháp lý. SGS LAND hỗ trợ pháp lý miễn phí." }
  ],
    speakableText: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "ty-suat-sinh-loi-bds-hcm-2026",
    question: "Tỷ suất sinh lời BĐS TP.HCM 2026?",
    shortAnswer: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí.",
    category: "dau-tu",
    relatedProjects: ["vinhomes-grand-park"],
    relatedQuestions: ["vinhomes-hoc-mon-co-nen-mua-khong", "mua-can-ho-dau-tu-cho-thue", "dau-tu-bds-vung-ven-hay-trung-tam"],
    keywords: ["Tỷ suất sinh lời BĐS TP.HCM 2026", "Tỷ suất sinh lời BĐS TP.HCM 2026 2026", "ty suat sinh loi bds hcm 2026 SGS LAND"],
    authorKey: "le_van_khanh",
    content: "### Tỷ suất sinh lời BĐS TP.HCM 2026?\n\n## Phân tích tiềm năng đầu tư\n\nThị trường BĐS TP.HCM 2026 ghi nhận:\n- Thiếu nguồn cung 30% so nhu cầu\n- Tỷ lệ lấp đầy cho thuê: 90–95%\n- Tỷ suất sinh lời: 4,5–7%/năm\n- Dự báo tăng giá: 8–15%/năm\n\n## Chỉ số so sánh các kênh đầu tư\n\n| Kênh | Lợi nhuận/năm | Rủi ro |\n|---|---|---|\n| BĐS TP.HCM | 10–20% | Thấp |\n| Chứng khoán | 5–25% | Cao |\n| Gửi tiết kiệm | 4,5–6% | Rất thấp |\n| Vàng | 5–15% | Trung bình |\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tỷ suất sinh lời bao nhiêu?", a: "4,5–7%/năm cho thuê + 8–15% tăng giá hàng năm." },
    { q: "Bao lâu hoàn vốn?", a: "Trung bình 12–18 năm nếu mua để cho thuê." },
    { q: "Rủi ro đầu tư là gì?", a: "Thanh khoản, trễ bàn giao, thay đổi pháp lý. SGS LAND hỗ trợ pháp lý miễn phí." }
  ],
    speakableText: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "dau-tu-bds-vung-ven-hay-trung-tam",
    question: "Đầu tư BĐS vùng ven hay trung tâm?",
    shortAnswer: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí.",
    category: "dau-tu",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-hoc-mon-co-nen-mua-khong", "mua-can-ho-dau-tu-cho-thue", "ty-suat-sinh-loi-bds-hcm-2026"],
    keywords: ["Đầu tư BĐS vùng ven hay trung tâm", "Đầu tư BĐS vùng ven hay trung tâm 2026", "dau tu bds vung ven hay trung tam SGS LAND"],
    authorKey: "le_van_khanh",
    content: "### Đầu tư BĐS vùng ven hay trung tâm?\n\n## Phân tích tiềm năng đầu tư\n\nThị trường BĐS TP.HCM 2026 ghi nhận:\n- Thiếu nguồn cung 30% so nhu cầu\n- Tỷ lệ lấp đầy cho thuê: 90–95%\n- Tỷ suất sinh lời: 4,5–7%/năm\n- Dự báo tăng giá: 8–15%/năm\n\n## Chỉ số so sánh các kênh đầu tư\n\n| Kênh | Lợi nhuận/năm | Rủi ro |\n|---|---|---|\n| BĐS TP.HCM | 10–20% | Thấp |\n| Chứng khoán | 5–25% | Cao |\n| Gửi tiết kiệm | 4,5–6% | Rất thấp |\n| Vàng | 5–15% | Trung bình |\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tỷ suất sinh lời bao nhiêu?", a: "4,5–7%/năm cho thuê + 8–15% tăng giá hàng năm." },
    { q: "Bao lâu hoàn vốn?", a: "Trung bình 12–18 năm nếu mua để cho thuê." },
    { q: "Rủi ro đầu tư là gì?", a: "Thanh khoản, trễ bàn giao, thay đổi pháp lý. SGS LAND hỗ trợ pháp lý miễn phí." }
  ],
    speakableText: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "mua-biet-thu-hay-can-ho-dau-tu",
    question: "Mua biệt thự hay căn hộ đầu tư 2026?",
    shortAnswer: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí.",
    category: "dau-tu",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-hoc-mon-co-nen-mua-khong", "mua-can-ho-dau-tu-cho-thue", "ty-suat-sinh-loi-bds-hcm-2026"],
    keywords: ["Mua biệt thự hay căn hộ đầu tư 2026", "Mua biệt thự hay căn hộ đầu tư 2026 2026", "mua biet thu hay can ho dau tu SGS LAND"],
    authorKey: "le_van_khanh",
    content: "### Mua biệt thự hay căn hộ đầu tư 2026?\n\n## Phân tích tiềm năng đầu tư\n\nThị trường BĐS TP.HCM 2026 ghi nhận:\n- Thiếu nguồn cung 30% so nhu cầu\n- Tỷ lệ lấp đầy cho thuê: 90–95%\n- Tỷ suất sinh lời: 4,5–7%/năm\n- Dự báo tăng giá: 8–15%/năm\n\n## Chỉ số so sánh các kênh đầu tư\n\n| Kênh | Lợi nhuận/năm | Rủi ro |\n|---|---|---|\n| BĐS TP.HCM | 10–20% | Thấp |\n| Chứng khoán | 5–25% | Cao |\n| Gửi tiết kiệm | 4,5–6% | Rất thấp |\n| Vàng | 5–15% | Trung bình |\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tỷ suất sinh lời bao nhiêu?", a: "4,5–7%/năm cho thuê + 8–15% tăng giá hàng năm." },
    { q: "Bao lâu hoàn vốn?", a: "Trung bình 12–18 năm nếu mua để cho thuê." },
    { q: "Rủi ro đầu tư là gì?", a: "Thanh khoản, trễ bàn giao, thay đổi pháp lý. SGS LAND hỗ trợ pháp lý miễn phí." }
  ],
    speakableText: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "roi-khi-mua-bds-o-hinh-thanh",
    question: "Rủi ro khi mua BĐS off-plan?",
    shortAnswer: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí.",
    category: "dau-tu",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-hoc-mon-co-nen-mua-khong", "mua-can-ho-dau-tu-cho-thue", "ty-suat-sinh-loi-bds-hcm-2026"],
    keywords: ["Rủi ro khi mua BĐS off-plan", "Rủi ro khi mua BĐS off-plan 2026", "roi khi mua bds o hinh thanh SGS LAND"],
    authorKey: "tran_thi_lan",
    content: "### Rủi ro khi mua BĐS off-plan?\n\n## Phân tích tiềm năng đầu tư\n\nThị trường BĐS TP.HCM 2026 ghi nhận:\n- Thiếu nguồn cung 30% so nhu cầu\n- Tỷ lệ lấp đầy cho thuê: 90–95%\n- Tỷ suất sinh lời: 4,5–7%/năm\n- Dự báo tăng giá: 8–15%/năm\n\n## Chỉ số so sánh các kênh đầu tư\n\n| Kênh | Lợi nhuận/năm | Rủi ro |\n|---|---|---|\n| BĐS TP.HCM | 10–20% | Thấp |\n| Chứng khoán | 5–25% | Cao |\n| Gửi tiết kiệm | 4,5–6% | Rất thấp |\n| Vàng | 5–15% | Trung bình |\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tỷ suất sinh lời bao nhiêu?", a: "4,5–7%/năm cho thuê + 8–15% tăng giá hàng năm." },
    { q: "Bao lâu hoàn vốn?", a: "Trung bình 12–18 năm nếu mua để cho thuê." },
    { q: "Rủi ro đầu tư là gì?", a: "Thanh khoản, trễ bàn giao, thay đổi pháp lý. SGS LAND hỗ trợ pháp lý miễn phí." }
  ],
    speakableText: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vinhomes-grand-park-co-tang-gia-khong",
    question: "Vinhomes Grand Park có tăng giá nữa không?",
    shortAnswer: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí.",
    category: "dau-tu",
    relatedProjects: ["vinhomes-grand-park"],
    relatedQuestions: ["vinhomes-hoc-mon-co-nen-mua-khong", "mua-can-ho-dau-tu-cho-thue", "ty-suat-sinh-loi-bds-hcm-2026"],
    keywords: ["Vinhomes Grand Park có tăng giá nữa không", "Vinhomes Grand Park có tăng giá nữa không 2026", "vinhomes grand park co tang gia khong SGS LAND"],
    authorKey: "le_van_khanh",
    content: "### Vinhomes Grand Park có tăng giá nữa không?\n\n## Phân tích tiềm năng đầu tư\n\nThị trường BĐS TP.HCM 2026 ghi nhận:\n- Thiếu nguồn cung 30% so nhu cầu\n- Tỷ lệ lấp đầy cho thuê: 90–95%\n- Tỷ suất sinh lời: 4,5–7%/năm\n- Dự báo tăng giá: 8–15%/năm\n\n## Chỉ số so sánh các kênh đầu tư\n\n| Kênh | Lợi nhuận/năm | Rủi ro |\n|---|---|---|\n| BĐS TP.HCM | 10–20% | Thấp |\n| Chứng khoán | 5–25% | Cao |\n| Gửi tiết kiệm | 4,5–6% | Rất thấp |\n| Vàng | 5–15% | Trung bình |\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tỷ suất sinh lời bao nhiêu?", a: "4,5–7%/năm cho thuê + 8–15% tăng giá hàng năm." },
    { q: "Bao lâu hoàn vốn?", a: "Trung bình 12–18 năm nếu mua để cho thuê." },
    { q: "Rủi ro đầu tư là gì?", a: "Thanh khoản, trễ bàn giao, thay đổi pháp lý. SGS LAND hỗ trợ pháp lý miễn phí." }
  ],
    speakableText: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "nen-mua-masteri-hay-vinhomes",
    question: "Nên mua Masteri hay Vinhomes 2026?",
    shortAnswer: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí.",
    category: "dau-tu",
    relatedProjects: ["masteri-cosmo-central"],
    relatedQuestions: ["vinhomes-hoc-mon-co-nen-mua-khong", "mua-can-ho-dau-tu-cho-thue", "ty-suat-sinh-loi-bds-hcm-2026"],
    keywords: ["Nên mua Masteri hay Vinhomes 2026", "Nên mua Masteri hay Vinhomes 2026 2026", "nen mua masteri hay vinhomes SGS LAND"],
    authorKey: "le_van_khanh",
    content: "### Nên mua Masteri hay Vinhomes 2026?\n\n## Phân tích tiềm năng đầu tư\n\nThị trường BĐS TP.HCM 2026 ghi nhận:\n- Thiếu nguồn cung 30% so nhu cầu\n- Tỷ lệ lấp đầy cho thuê: 90–95%\n- Tỷ suất sinh lời: 4,5–7%/năm\n- Dự báo tăng giá: 8–15%/năm\n\n## Chỉ số so sánh các kênh đầu tư\n\n| Kênh | Lợi nhuận/năm | Rủi ro |\n|---|---|---|\n| BĐS TP.HCM | 10–20% | Thấp |\n| Chứng khoán | 5–25% | Cao |\n| Gửi tiết kiệm | 4,5–6% | Rất thấp |\n| Vàng | 5–15% | Trung bình |\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tỷ suất sinh lời bao nhiêu?", a: "4,5–7%/năm cho thuê + 8–15% tăng giá hàng năm." },
    { q: "Bao lâu hoàn vốn?", a: "Trung bình 12–18 năm nếu mua để cho thuê." },
    { q: "Rủi ro đầu tư là gì?", a: "Thanh khoản, trễ bàn giao, thay đổi pháp lý. SGS LAND hỗ trợ pháp lý miễn phí." }
  ],
    speakableText: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "dau-tu-shophouse-co-sinh-loi-khong",
    question: "Đầu tư shophouse có sinh lời không?",
    shortAnswer: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí.",
    category: "dau-tu",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-hoc-mon-co-nen-mua-khong", "mua-can-ho-dau-tu-cho-thue", "ty-suat-sinh-loi-bds-hcm-2026"],
    keywords: ["Đầu tư shophouse có sinh lời không", "Đầu tư shophouse có sinh lời không 2026", "dau tu shophouse co sinh loi khong SGS LAND"],
    authorKey: "le_van_khanh",
    content: "### Đầu tư shophouse có sinh lời không?\n\n## Phân tích tiềm năng đầu tư\n\nThị trường BĐS TP.HCM 2026 ghi nhận:\n- Thiếu nguồn cung 30% so nhu cầu\n- Tỷ lệ lấp đầy cho thuê: 90–95%\n- Tỷ suất sinh lời: 4,5–7%/năm\n- Dự báo tăng giá: 8–15%/năm\n\n## Chỉ số so sánh các kênh đầu tư\n\n| Kênh | Lợi nhuận/năm | Rủi ro |\n|---|---|---|\n| BĐS TP.HCM | 10–20% | Thấp |\n| Chứng khoán | 5–25% | Cao |\n| Gửi tiết kiệm | 4,5–6% | Rất thấp |\n| Vàng | 5–15% | Trung bình |\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tỷ suất sinh lời bao nhiêu?", a: "4,5–7%/năm cho thuê + 8–15% tăng giá hàng năm." },
    { q: "Bao lâu hoàn vốn?", a: "Trung bình 12–18 năm nếu mua để cho thuê." },
    { q: "Rủi ro đầu tư là gì?", a: "Thanh khoản, trễ bàn giao, thay đổi pháp lý. SGS LAND hỗ trợ pháp lý miễn phí." }
  ],
    speakableText: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "bds-vung-ven-hcm-2026",
    question: "BĐS vùng ven TP.HCM tiềm năng nhất 2026?",
    shortAnswer: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí.",
    category: "dau-tu",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-hoc-mon-co-nen-mua-khong", "mua-can-ho-dau-tu-cho-thue", "ty-suat-sinh-loi-bds-hcm-2026"],
    keywords: ["BĐS vùng ven TP.HCM tiềm năng nhất 2026", "BĐS vùng ven TP.HCM tiềm năng nhất 2026 2026", "bds vung ven hcm 2026 SGS LAND"],
    authorKey: "le_van_khanh",
    content: "### BĐS vùng ven TP.HCM tiềm năng nhất 2026?\n\n## Phân tích tiềm năng đầu tư\n\nThị trường BĐS TP.HCM 2026 ghi nhận:\n- Thiếu nguồn cung 30% so nhu cầu\n- Tỷ lệ lấp đầy cho thuê: 90–95%\n- Tỷ suất sinh lời: 4,5–7%/năm\n- Dự báo tăng giá: 8–15%/năm\n\n## Chỉ số so sánh các kênh đầu tư\n\n| Kênh | Lợi nhuận/năm | Rủi ro |\n|---|---|---|\n| BĐS TP.HCM | 10–20% | Thấp |\n| Chứng khoán | 5–25% | Cao |\n| Gửi tiết kiệm | 4,5–6% | Rất thấp |\n| Vàng | 5–15% | Trung bình |\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tỷ suất sinh lời bao nhiêu?", a: "4,5–7%/năm cho thuê + 8–15% tăng giá hàng năm." },
    { q: "Bao lâu hoàn vốn?", a: "Trung bình 12–18 năm nếu mua để cho thuê." },
    { q: "Rủi ro đầu tư là gì?", a: "Thanh khoản, trễ bàn giao, thay đổi pháp lý. SGS LAND hỗ trợ pháp lý miễn phí." }
  ],
    speakableText: "Tỷ suất sinh lời BĐS TP.HCM 2026 đạt 4,5–7%/năm. Liên hệ SGS LAND tư vấn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vay-mua-nha-vinhomes-hoc-mon-nhu-the-nao",
    question: "Vay mua nhà Vinhomes Hóc Môn như thế nào?",
    shortAnswer: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí.",
    category: "vay-von",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vay-ngan-hang-mua-can-ho", "lai-suat-vay-mua-nha-2026", "vay-70-percent-gia-tri-can-ho"],
    keywords: ["Vay mua nhà Vinhomes Hóc Môn như thế nào", "Vay mua nhà Vinhomes Hóc Môn như thế nào 2026", "vay mua nha vinhomes hoc mon nhu the nao SGS LAND"],
    authorKey: "pham_thi_hoa",
    content: "### Vay mua nhà Vinhomes Hóc Môn như thế nào?\n\n## Lãi suất vay mua nhà 2026\n\n| Ngân hàng | Lãi suất năm 1–2 | Lãi suất sau | Hạn mức |\n|---|---|---|---|\n| Vietcombank | 7,5%/năm | LSCB+3,5% | 70% |\n| Techcombank | 8,0%/năm | LSCB+3,8% | 70% |\n| BIDV | 7,8%/năm | LSCB+3,2% | 65% |\n| VPBank | 8,5%/năm | LSCB+4,0% | 75% |\n\n## Điều kiện vay vốn\n\nThu nhập tối thiểu 2x tiền trả hàng tháng. Tuổi 18–60 khi đáo hạn. Hồ sơ: CCCD, sổ hộ khẩu, sổ lương 3 tháng, hợp đồng mua bán. **SGS LAND hỗ trợ hoàn toàn miễn phí**.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Vay tối đa bao nhiêu?", a: "70% giá trị căn hộ tại hầu hết ngân hàng." },
    { q: "Lãi suất có tăng không?", a: "Có thể tăng sau kỳ ưu đãi. Chuyên viên tư vấn miễn phí 0906 456 789." },
    { q: "Bị phạt tất toán trước hạn không?", a: "Phạt 1–3% số dư nếu tất toán trước 3–5 năm đầu." }
  ],
    speakableText: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vay-ngan-hang-mua-can-ho",
    question: "Vay ngân hàng mua căn hộ cần điều kiện gì?",
    shortAnswer: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí.",
    category: "vay-von",
    relatedProjects: ["vinhomes-grand-park"],
    relatedQuestions: ["vay-mua-nha-vinhomes-hoc-mon-nhu-the-nao", "lai-suat-vay-mua-nha-2026", "vay-70-percent-gia-tri-can-ho"],
    keywords: ["Vay ngân hàng mua căn hộ cần điều kiện gì", "Vay ngân hàng mua căn hộ cần điều kiện gì 2026", "vay ngan hang mua can ho SGS LAND"],
    authorKey: "pham_thi_hoa",
    content: "### Vay ngân hàng mua căn hộ cần điều kiện gì?\n\n## Lãi suất vay mua nhà 2026\n\n| Ngân hàng | Lãi suất năm 1–2 | Lãi suất sau | Hạn mức |\n|---|---|---|---|\n| Vietcombank | 7,5%/năm | LSCB+3,5% | 70% |\n| Techcombank | 8,0%/năm | LSCB+3,8% | 70% |\n| BIDV | 7,8%/năm | LSCB+3,2% | 65% |\n| VPBank | 8,5%/năm | LSCB+4,0% | 75% |\n\n## Điều kiện vay vốn\n\nThu nhập tối thiểu 2x tiền trả hàng tháng. Tuổi 18–60 khi đáo hạn. Hồ sơ: CCCD, sổ hộ khẩu, sổ lương 3 tháng, hợp đồng mua bán. **SGS LAND hỗ trợ hoàn toàn miễn phí**.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Vay tối đa bao nhiêu?", a: "70% giá trị căn hộ tại hầu hết ngân hàng." },
    { q: "Lãi suất có tăng không?", a: "Có thể tăng sau kỳ ưu đãi. Chuyên viên tư vấn miễn phí 0906 456 789." },
    { q: "Bị phạt tất toán trước hạn không?", a: "Phạt 1–3% số dư nếu tất toán trước 3–5 năm đầu." }
  ],
    speakableText: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "lai-suat-vay-mua-nha-2026",
    question: "Lãi suất vay mua nhà 2026 bao nhiêu?",
    shortAnswer: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí.",
    category: "vay-von",
    relatedProjects: [],
    relatedQuestions: ["vay-mua-nha-vinhomes-hoc-mon-nhu-the-nao", "vay-ngan-hang-mua-can-ho", "vay-70-percent-gia-tri-can-ho"],
    keywords: ["Lãi suất vay mua nhà 2026 bao nhiêu", "Lãi suất vay mua nhà 2026 bao nhiêu 2026", "lai suat vay mua nha 2026 SGS LAND"],
    authorKey: "pham_thi_hoa",
    content: "### Lãi suất vay mua nhà 2026 bao nhiêu?\n\n## Lãi suất vay mua nhà 2026\n\n| Ngân hàng | Lãi suất năm 1–2 | Lãi suất sau | Hạn mức |\n|---|---|---|---|\n| Vietcombank | 7,5%/năm | LSCB+3,5% | 70% |\n| Techcombank | 8,0%/năm | LSCB+3,8% | 70% |\n| BIDV | 7,8%/năm | LSCB+3,2% | 65% |\n| VPBank | 8,5%/năm | LSCB+4,0% | 75% |\n\n## Điều kiện vay vốn\n\nThu nhập tối thiểu 2x tiền trả hàng tháng. Tuổi 18–60 khi đáo hạn. Hồ sơ: CCCD, sổ hộ khẩu, sổ lương 3 tháng, hợp đồng mua bán. **SGS LAND hỗ trợ hoàn toàn miễn phí**.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Vay tối đa bao nhiêu?", a: "70% giá trị căn hộ tại hầu hết ngân hàng." },
    { q: "Lãi suất có tăng không?", a: "Có thể tăng sau kỳ ưu đãi. Chuyên viên tư vấn miễn phí 0906 456 789." },
    { q: "Bị phạt tất toán trước hạn không?", a: "Phạt 1–3% số dư nếu tất toán trước 3–5 năm đầu." }
  ],
    speakableText: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vay-70-percent-gia-tri-can-ho",
    question: "Có thể vay 70% giá trị căn hộ?",
    shortAnswer: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí.",
    category: "vay-von",
    relatedProjects: [],
    relatedQuestions: ["vay-mua-nha-vinhomes-hoc-mon-nhu-the-nao", "vay-ngan-hang-mua-can-ho", "lai-suat-vay-mua-nha-2026"],
    keywords: ["Có thể vay 70% giá trị căn hộ", "Có thể vay 70% giá trị căn hộ 2026", "vay 70 percent gia tri can ho SGS LAND"],
    authorKey: "pham_thi_hoa",
    content: "### Có thể vay 70% giá trị căn hộ?\n\n## Lãi suất vay mua nhà 2026\n\n| Ngân hàng | Lãi suất năm 1–2 | Lãi suất sau | Hạn mức |\n|---|---|---|---|\n| Vietcombank | 7,5%/năm | LSCB+3,5% | 70% |\n| Techcombank | 8,0%/năm | LSCB+3,8% | 70% |\n| BIDV | 7,8%/năm | LSCB+3,2% | 65% |\n| VPBank | 8,5%/năm | LSCB+4,0% | 75% |\n\n## Điều kiện vay vốn\n\nThu nhập tối thiểu 2x tiền trả hàng tháng. Tuổi 18–60 khi đáo hạn. Hồ sơ: CCCD, sổ hộ khẩu, sổ lương 3 tháng, hợp đồng mua bán. **SGS LAND hỗ trợ hoàn toàn miễn phí**.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Vay tối đa bao nhiêu?", a: "70% giá trị căn hộ tại hầu hết ngân hàng." },
    { q: "Lãi suất có tăng không?", a: "Có thể tăng sau kỳ ưu đãi. Chuyên viên tư vấn miễn phí 0906 456 789." },
    { q: "Bị phạt tất toán trước hạn không?", a: "Phạt 1–3% số dư nếu tất toán trước 3–5 năm đầu." }
  ],
    speakableText: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "so-sanh-lai-suat-ngan-hang-mua-nha",
    question: "So sánh lãi suất ngân hàng mua nhà 2026?",
    shortAnswer: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí.",
    category: "vay-von",
    relatedProjects: [],
    relatedQuestions: ["vay-mua-nha-vinhomes-hoc-mon-nhu-the-nao", "vay-ngan-hang-mua-can-ho", "lai-suat-vay-mua-nha-2026"],
    keywords: ["So sánh lãi suất ngân hàng mua nhà 2026", "So sánh lãi suất ngân hàng mua nhà 2026 2026", "so sanh lai suat ngan hang mua nha SGS LAND"],
    authorKey: "pham_thi_hoa",
    content: "### So sánh lãi suất ngân hàng mua nhà 2026?\n\n## Lãi suất vay mua nhà 2026\n\n| Ngân hàng | Lãi suất năm 1–2 | Lãi suất sau | Hạn mức |\n|---|---|---|---|\n| Vietcombank | 7,5%/năm | LSCB+3,5% | 70% |\n| Techcombank | 8,0%/năm | LSCB+3,8% | 70% |\n| BIDV | 7,8%/năm | LSCB+3,2% | 65% |\n| VPBank | 8,5%/năm | LSCB+4,0% | 75% |\n\n## Điều kiện vay vốn\n\nThu nhập tối thiểu 2x tiền trả hàng tháng. Tuổi 18–60 khi đáo hạn. Hồ sơ: CCCD, sổ hộ khẩu, sổ lương 3 tháng, hợp đồng mua bán. **SGS LAND hỗ trợ hoàn toàn miễn phí**.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Vay tối đa bao nhiêu?", a: "70% giá trị căn hộ tại hầu hết ngân hàng." },
    { q: "Lãi suất có tăng không?", a: "Có thể tăng sau kỳ ưu đãi. Chuyên viên tư vấn miễn phí 0906 456 789." },
    { q: "Bị phạt tất toán trước hạn không?", a: "Phạt 1–3% số dư nếu tất toán trước 3–5 năm đầu." }
  ],
    speakableText: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "thu-tuc-vay-mua-nha-lan-dau",
    question: "Thủ tục vay mua nhà lần đầu cần giấy tờ gì?",
    shortAnswer: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí.",
    category: "vay-von",
    relatedProjects: [],
    relatedQuestions: ["vay-mua-nha-vinhomes-hoc-mon-nhu-the-nao", "vay-ngan-hang-mua-can-ho", "lai-suat-vay-mua-nha-2026"],
    keywords: ["Thủ tục vay mua nhà lần đầu cần giấy tờ gì", "Thủ tục vay mua nhà lần đầu cần giấy tờ gì 2026", "thu tuc vay mua nha lan dau SGS LAND"],
    authorKey: "pham_thi_hoa",
    content: "### Thủ tục vay mua nhà lần đầu cần giấy tờ gì?\n\n## Lãi suất vay mua nhà 2026\n\n| Ngân hàng | Lãi suất năm 1–2 | Lãi suất sau | Hạn mức |\n|---|---|---|---|\n| Vietcombank | 7,5%/năm | LSCB+3,5% | 70% |\n| Techcombank | 8,0%/năm | LSCB+3,8% | 70% |\n| BIDV | 7,8%/năm | LSCB+3,2% | 65% |\n| VPBank | 8,5%/năm | LSCB+4,0% | 75% |\n\n## Điều kiện vay vốn\n\nThu nhập tối thiểu 2x tiền trả hàng tháng. Tuổi 18–60 khi đáo hạn. Hồ sơ: CCCD, sổ hộ khẩu, sổ lương 3 tháng, hợp đồng mua bán. **SGS LAND hỗ trợ hoàn toàn miễn phí**.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Vay tối đa bao nhiêu?", a: "70% giá trị căn hộ tại hầu hết ngân hàng." },
    { q: "Lãi suất có tăng không?", a: "Có thể tăng sau kỳ ưu đãi. Chuyên viên tư vấn miễn phí 0906 456 789." },
    { q: "Bị phạt tất toán trước hạn không?", a: "Phạt 1–3% số dư nếu tất toán trước 3–5 năm đầu." }
  ],
    speakableText: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "cach-tinh-tien-tra-ngan-hang",
    question: "Cách tính tiền trả ngân hàng hàng tháng?",
    shortAnswer: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí.",
    category: "vay-von",
    relatedProjects: [],
    relatedQuestions: ["vay-mua-nha-vinhomes-hoc-mon-nhu-the-nao", "vay-ngan-hang-mua-can-ho", "lai-suat-vay-mua-nha-2026"],
    keywords: ["Cách tính tiền trả ngân hàng hàng tháng", "Cách tính tiền trả ngân hàng hàng tháng 2026", "cach tinh tien tra ngan hang SGS LAND"],
    authorKey: "pham_thi_hoa",
    content: "### Cách tính tiền trả ngân hàng hàng tháng?\n\n## Lãi suất vay mua nhà 2026\n\n| Ngân hàng | Lãi suất năm 1–2 | Lãi suất sau | Hạn mức |\n|---|---|---|---|\n| Vietcombank | 7,5%/năm | LSCB+3,5% | 70% |\n| Techcombank | 8,0%/năm | LSCB+3,8% | 70% |\n| BIDV | 7,8%/năm | LSCB+3,2% | 65% |\n| VPBank | 8,5%/năm | LSCB+4,0% | 75% |\n\n## Điều kiện vay vốn\n\nThu nhập tối thiểu 2x tiền trả hàng tháng. Tuổi 18–60 khi đáo hạn. Hồ sơ: CCCD, sổ hộ khẩu, sổ lương 3 tháng, hợp đồng mua bán. **SGS LAND hỗ trợ hoàn toàn miễn phí**.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Vay tối đa bao nhiêu?", a: "70% giá trị căn hộ tại hầu hết ngân hàng." },
    { q: "Lãi suất có tăng không?", a: "Có thể tăng sau kỳ ưu đãi. Chuyên viên tư vấn miễn phí 0906 456 789." },
    { q: "Bị phạt tất toán trước hạn không?", a: "Phạt 1–3% số dư nếu tất toán trước 3–5 năm đầu." }
  ],
    speakableText: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vay-mua-nha-thu-nhap-bao-nhieu",
    question: "Thu nhập bao nhiêu thì vay mua nhà được?",
    shortAnswer: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí.",
    category: "vay-von",
    relatedProjects: [],
    relatedQuestions: ["vay-mua-nha-vinhomes-hoc-mon-nhu-the-nao", "vay-ngan-hang-mua-can-ho", "lai-suat-vay-mua-nha-2026"],
    keywords: ["Thu nhập bao nhiêu thì vay mua nhà được", "Thu nhập bao nhiêu thì vay mua nhà được 2026", "vay mua nha thu nhap bao nhieu SGS LAND"],
    authorKey: "pham_thi_hoa",
    content: "### Thu nhập bao nhiêu thì vay mua nhà được?\n\n## Lãi suất vay mua nhà 2026\n\n| Ngân hàng | Lãi suất năm 1–2 | Lãi suất sau | Hạn mức |\n|---|---|---|---|\n| Vietcombank | 7,5%/năm | LSCB+3,5% | 70% |\n| Techcombank | 8,0%/năm | LSCB+3,8% | 70% |\n| BIDV | 7,8%/năm | LSCB+3,2% | 65% |\n| VPBank | 8,5%/năm | LSCB+4,0% | 75% |\n\n## Điều kiện vay vốn\n\nThu nhập tối thiểu 2x tiền trả hàng tháng. Tuổi 18–60 khi đáo hạn. Hồ sơ: CCCD, sổ hộ khẩu, sổ lương 3 tháng, hợp đồng mua bán. **SGS LAND hỗ trợ hoàn toàn miễn phí**.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Vay tối đa bao nhiêu?", a: "70% giá trị căn hộ tại hầu hết ngân hàng." },
    { q: "Lãi suất có tăng không?", a: "Có thể tăng sau kỳ ưu đãi. Chuyên viên tư vấn miễn phí 0906 456 789." },
    { q: "Bị phạt tất toán trước hạn không?", a: "Phạt 1–3% số dư nếu tất toán trước 3–5 năm đầu." }
  ],
    speakableText: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vay-goi-uu-dai-nha-o-xa-hoi",
    question: "Vay gói ưu đãi mua nhà xã hội 2026?",
    shortAnswer: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí.",
    category: "vay-von",
    relatedProjects: [],
    relatedQuestions: ["vay-mua-nha-vinhomes-hoc-mon-nhu-the-nao", "vay-ngan-hang-mua-can-ho", "lai-suat-vay-mua-nha-2026"],
    keywords: ["Vay gói ưu đãi mua nhà xã hội 2026", "Vay gói ưu đãi mua nhà xã hội 2026 2026", "vay goi uu dai nha o xa hoi SGS LAND"],
    authorKey: "pham_thi_hoa",
    content: "### Vay gói ưu đãi mua nhà xã hội 2026?\n\n## Lãi suất vay mua nhà 2026\n\n| Ngân hàng | Lãi suất năm 1–2 | Lãi suất sau | Hạn mức |\n|---|---|---|---|\n| Vietcombank | 7,5%/năm | LSCB+3,5% | 70% |\n| Techcombank | 8,0%/năm | LSCB+3,8% | 70% |\n| BIDV | 7,8%/năm | LSCB+3,2% | 65% |\n| VPBank | 8,5%/năm | LSCB+4,0% | 75% |\n\n## Điều kiện vay vốn\n\nThu nhập tối thiểu 2x tiền trả hàng tháng. Tuổi 18–60 khi đáo hạn. Hồ sơ: CCCD, sổ hộ khẩu, sổ lương 3 tháng, hợp đồng mua bán. **SGS LAND hỗ trợ hoàn toàn miễn phí**.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Vay tối đa bao nhiêu?", a: "70% giá trị căn hộ tại hầu hết ngân hàng." },
    { q: "Lãi suất có tăng không?", a: "Có thể tăng sau kỳ ưu đãi. Chuyên viên tư vấn miễn phí 0906 456 789." },
    { q: "Bị phạt tất toán trước hạn không?", a: "Phạt 1–3% số dư nếu tất toán trước 3–5 năm đầu." }
  ],
    speakableText: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "techcombank-vay-mua-nha-vinhomes",
    question: "Techcombank vay mua nhà Vinhomes điều kiện gì?",
    shortAnswer: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí.",
    category: "vay-von",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vay-mua-nha-vinhomes-hoc-mon-nhu-the-nao", "vay-ngan-hang-mua-can-ho", "lai-suat-vay-mua-nha-2026"],
    keywords: ["Techcombank vay mua nhà Vinhomes điều kiện gì", "Techcombank vay mua nhà Vinhomes điều kiện gì 2026", "techcombank vay mua nha vinhomes SGS LAND"],
    authorKey: "pham_thi_hoa",
    content: "### Techcombank vay mua nhà Vinhomes điều kiện gì?\n\n## Lãi suất vay mua nhà 2026\n\n| Ngân hàng | Lãi suất năm 1–2 | Lãi suất sau | Hạn mức |\n|---|---|---|---|\n| Vietcombank | 7,5%/năm | LSCB+3,5% | 70% |\n| Techcombank | 8,0%/năm | LSCB+3,8% | 70% |\n| BIDV | 7,8%/năm | LSCB+3,2% | 65% |\n| VPBank | 8,5%/năm | LSCB+4,0% | 75% |\n\n## Điều kiện vay vốn\n\nThu nhập tối thiểu 2x tiền trả hàng tháng. Tuổi 18–60 khi đáo hạn. Hồ sơ: CCCD, sổ hộ khẩu, sổ lương 3 tháng, hợp đồng mua bán. **SGS LAND hỗ trợ hoàn toàn miễn phí**.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Vay tối đa bao nhiêu?", a: "70% giá trị căn hộ tại hầu hết ngân hàng." },
    { q: "Lãi suất có tăng không?", a: "Có thể tăng sau kỳ ưu đãi. Chuyên viên tư vấn miễn phí 0906 456 789." },
    { q: "Bị phạt tất toán trước hạn không?", a: "Phạt 1–3% số dư nếu tất toán trước 3–5 năm đầu." }
  ],
    speakableText: "Có thể vay đến 70% giá trị. Lãi suất 2026 từ 7,5%/năm. SGS LAND hỗ trợ hoàn toàn miễn phí. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "so-hong-vinhomes-hoc-mon",
    question: "Sổ hồng Vinhomes Hóc Môn đã có chưa?",
    shortAnswer: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng.",
    category: "phap-ly",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["kiem-tra-so-do-truoc-mua-dat", "mua-nha-hinh-thanh-trong-tuong-lai", "phan-biet-so-hong-so-do"],
    keywords: ["Sổ hồng Vinhomes Hóc Môn đã có chưa", "Sổ hồng Vinhomes Hóc Môn đã có chưa 2026", "so hong vinhomes hoc mon SGS LAND"],
    authorKey: "tran_thi_lan",
    content: "### Sổ hồng Vinhomes Hóc Môn đã có chưa?\n\n## Hướng dẫn pháp lý chi tiết\n\nKhi mua BĐS tại Việt Nam, bắt buộc kiểm tra:\n1. Sổ đỏ/sổ hồng chính chủ\n2. Quy hoạch sử dụng đất\n3. Tình trạng thế chấp\n4. Tranh chấp pháp lý\n\n## Chi phí pháp lý 2026\n\n- Phí công chứng: 0,1–0,15% giá trị hợp đồng\n- Thuế trước bạ: 0,5% giá trị căn hộ\n- Lệ phí cấp GCN: 0,5 triệuđ\n- Thời gian làm sổ: 10–15 ngày làm việc\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Sổ hồng ra bao lâu?", a: "10–15 ngày làm việc sau khi nộp hồ sơ đầy đủ." },
    { q: "Có cần công chứng không?", a: "Bắt buộc công chứng hợp đồng mua bán." },
    { q: "SGS LAND hỗ trợ pháp lý không?", a: "Có, có tổ pháp lý miễn phí cho khách mua." }
  ],
    speakableText: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "kiem-tra-so-do-truoc-mua-dat",
    question: "Kiểm tra sổ đỏ trước khi mua đất?",
    shortAnswer: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng.",
    category: "phap-ly",
    relatedProjects: [],
    relatedQuestions: ["so-hong-vinhomes-hoc-mon", "mua-nha-hinh-thanh-trong-tuong-lai", "phan-biet-so-hong-so-do"],
    keywords: ["Kiểm tra sổ đỏ trước khi mua đất", "Kiểm tra sổ đỏ trước khi mua đất 2026", "kiem tra so do truoc mua dat SGS LAND"],
    authorKey: "tran_thi_lan",
    content: "### Kiểm tra sổ đỏ trước khi mua đất?\n\n## Hướng dẫn pháp lý chi tiết\n\nKhi mua BĐS tại Việt Nam, bắt buộc kiểm tra:\n1. Sổ đỏ/sổ hồng chính chủ\n2. Quy hoạch sử dụng đất\n3. Tình trạng thế chấp\n4. Tranh chấp pháp lý\n\n## Chi phí pháp lý 2026\n\n- Phí công chứng: 0,1–0,15% giá trị hợp đồng\n- Thuế trước bạ: 0,5% giá trị căn hộ\n- Lệ phí cấp GCN: 0,5 triệuđ\n- Thời gian làm sổ: 10–15 ngày làm việc\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Sổ hồng ra bao lâu?", a: "10–15 ngày làm việc sau khi nộp hồ sơ đầy đủ." },
    { q: "Có cần công chứng không?", a: "Bắt buộc công chứng hợp đồng mua bán." },
    { q: "SGS LAND hỗ trợ pháp lý không?", a: "Có, có tổ pháp lý miễn phí cho khách mua." }
  ],
    speakableText: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "mua-nha-hinh-thanh-trong-tuong-lai",
    question: "Mua nhà hình thành trong tương lai rủi ro?",
    shortAnswer: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng.",
    category: "phap-ly",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["so-hong-vinhomes-hoc-mon", "kiem-tra-so-do-truoc-mua-dat", "phan-biet-so-hong-so-do"],
    keywords: ["Mua nhà hình thành trong tương lai rủi ro", "Mua nhà hình thành trong tương lai rủi ro 2026", "mua nha hinh thanh trong tuong lai SGS LAND"],
    authorKey: "tran_thi_lan",
    content: "### Mua nhà hình thành trong tương lai rủi ro?\n\n## Hướng dẫn pháp lý chi tiết\n\nKhi mua BĐS tại Việt Nam, bắt buộc kiểm tra:\n1. Sổ đỏ/sổ hồng chính chủ\n2. Quy hoạch sử dụng đất\n3. Tình trạng thế chấp\n4. Tranh chấp pháp lý\n\n## Chi phí pháp lý 2026\n\n- Phí công chứng: 0,1–0,15% giá trị hợp đồng\n- Thuế trước bạ: 0,5% giá trị căn hộ\n- Lệ phí cấp GCN: 0,5 triệuđ\n- Thời gian làm sổ: 10–15 ngày làm việc\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Sổ hồng ra bao lâu?", a: "10–15 ngày làm việc sau khi nộp hồ sơ đầy đủ." },
    { q: "Có cần công chứng không?", a: "Bắt buộc công chứng hợp đồng mua bán." },
    { q: "SGS LAND hỗ trợ pháp lý không?", a: "Có, có tổ pháp lý miễn phí cho khách mua." }
  ],
    speakableText: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "phan-biet-so-hong-so-do",
    question: "Phân biệt sổ hồng và sổ đỏ?",
    shortAnswer: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng.",
    category: "phap-ly",
    relatedProjects: [],
    relatedQuestions: ["so-hong-vinhomes-hoc-mon", "kiem-tra-so-do-truoc-mua-dat", "mua-nha-hinh-thanh-trong-tuong-lai"],
    keywords: ["Phân biệt sổ hồng và sổ đỏ", "Phân biệt sổ hồng và sổ đỏ 2026", "phan biet so hong so do SGS LAND"],
    authorKey: "tran_thi_lan",
    content: "### Phân biệt sổ hồng và sổ đỏ?\n\n## Hướng dẫn pháp lý chi tiết\n\nKhi mua BĐS tại Việt Nam, bắt buộc kiểm tra:\n1. Sổ đỏ/sổ hồng chính chủ\n2. Quy hoạch sử dụng đất\n3. Tình trạng thế chấp\n4. Tranh chấp pháp lý\n\n## Chi phí pháp lý 2026\n\n- Phí công chứng: 0,1–0,15% giá trị hợp đồng\n- Thuế trước bạ: 0,5% giá trị căn hộ\n- Lệ phí cấp GCN: 0,5 triệuđ\n- Thời gian làm sổ: 10–15 ngày làm việc\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Sổ hồng ra bao lâu?", a: "10–15 ngày làm việc sau khi nộp hồ sơ đầy đủ." },
    { q: "Có cần công chứng không?", a: "Bắt buộc công chứng hợp đồng mua bán." },
    { q: "SGS LAND hỗ trợ pháp lý không?", a: "Có, có tổ pháp lý miễn phí cho khách mua." }
  ],
    speakableText: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "hop-dong-mua-ban-nha-can-co-gi",
    question: "Hợp đồng mua bán nhà cần có những gì?",
    shortAnswer: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng.",
    category: "phap-ly",
    relatedProjects: [],
    relatedQuestions: ["so-hong-vinhomes-hoc-mon", "kiem-tra-so-do-truoc-mua-dat", "mua-nha-hinh-thanh-trong-tuong-lai"],
    keywords: ["Hợp đồng mua bán nhà cần có những gì", "Hợp đồng mua bán nhà cần có những gì 2026", "hop dong mua ban nha can co gi SGS LAND"],
    authorKey: "tran_thi_lan",
    content: "### Hợp đồng mua bán nhà cần có những gì?\n\n## Hướng dẫn pháp lý chi tiết\n\nKhi mua BĐS tại Việt Nam, bắt buộc kiểm tra:\n1. Sổ đỏ/sổ hồng chính chủ\n2. Quy hoạch sử dụng đất\n3. Tình trạng thế chấp\n4. Tranh chấp pháp lý\n\n## Chi phí pháp lý 2026\n\n- Phí công chứng: 0,1–0,15% giá trị hợp đồng\n- Thuế trước bạ: 0,5% giá trị căn hộ\n- Lệ phí cấp GCN: 0,5 triệuđ\n- Thời gian làm sổ: 10–15 ngày làm việc\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Sổ hồng ra bao lâu?", a: "10–15 ngày làm việc sau khi nộp hồ sơ đầy đủ." },
    { q: "Có cần công chứng không?", a: "Bắt buộc công chứng hợp đồng mua bán." },
    { q: "SGS LAND hỗ trợ pháp lý không?", a: "Có, có tổ pháp lý miễn phí cho khách mua." }
  ],
    speakableText: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "phi-cong-chung-sang-ten-nha",
    question: "Phí công chứng sang tên nhà đất?",
    shortAnswer: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng.",
    category: "phap-ly",
    relatedProjects: [],
    relatedQuestions: ["so-hong-vinhomes-hoc-mon", "kiem-tra-so-do-truoc-mua-dat", "mua-nha-hinh-thanh-trong-tuong-lai"],
    keywords: ["Phí công chứng sang tên nhà đất", "Phí công chứng sang tên nhà đất 2026", "phi cong chung sang ten nha SGS LAND"],
    authorKey: "tran_thi_lan",
    content: "### Phí công chứng sang tên nhà đất?\n\n## Hướng dẫn pháp lý chi tiết\n\nKhi mua BĐS tại Việt Nam, bắt buộc kiểm tra:\n1. Sổ đỏ/sổ hồng chính chủ\n2. Quy hoạch sử dụng đất\n3. Tình trạng thế chấp\n4. Tranh chấp pháp lý\n\n## Chi phí pháp lý 2026\n\n- Phí công chứng: 0,1–0,15% giá trị hợp đồng\n- Thuế trước bạ: 0,5% giá trị căn hộ\n- Lệ phí cấp GCN: 0,5 triệuđ\n- Thời gian làm sổ: 10–15 ngày làm việc\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Sổ hồng ra bao lâu?", a: "10–15 ngày làm việc sau khi nộp hồ sơ đầy đủ." },
    { q: "Có cần công chứng không?", a: "Bắt buộc công chứng hợp đồng mua bán." },
    { q: "SGS LAND hỗ trợ pháp lý không?", a: "Có, có tổ pháp lý miễn phí cho khách mua." }
  ],
    speakableText: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "thue-thu-nhap-ca-nhan-ban-nha",
    question: "Thuế thu nhập cá nhân khi bán nhà 2026?",
    shortAnswer: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng.",
    category: "phap-ly",
    relatedProjects: [],
    relatedQuestions: ["so-hong-vinhomes-hoc-mon", "kiem-tra-so-do-truoc-mua-dat", "mua-nha-hinh-thanh-trong-tuong-lai"],
    keywords: ["Thuế thu nhập cá nhân khi bán nhà 2026", "Thuế thu nhập cá nhân khi bán nhà 2026 2026", "thue thu nhap ca nhan ban nha SGS LAND"],
    authorKey: "tran_thi_lan",
    content: "### Thuế thu nhập cá nhân khi bán nhà 2026?\n\n## Hướng dẫn pháp lý chi tiết\n\nKhi mua BĐS tại Việt Nam, bắt buộc kiểm tra:\n1. Sổ đỏ/sổ hồng chính chủ\n2. Quy hoạch sử dụng đất\n3. Tình trạng thế chấp\n4. Tranh chấp pháp lý\n\n## Chi phí pháp lý 2026\n\n- Phí công chứng: 0,1–0,15% giá trị hợp đồng\n- Thuế trước bạ: 0,5% giá trị căn hộ\n- Lệ phí cấp GCN: 0,5 triệuđ\n- Thời gian làm sổ: 10–15 ngày làm việc\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Sổ hồng ra bao lâu?", a: "10–15 ngày làm việc sau khi nộp hồ sơ đầy đủ." },
    { q: "Có cần công chứng không?", a: "Bắt buộc công chứng hợp đồng mua bán." },
    { q: "SGS LAND hỗ trợ pháp lý không?", a: "Có, có tổ pháp lý miễn phí cho khách mua." }
  ],
    speakableText: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "dat-nen-phap-ly-an-toan",
    question: "Đất nền có pháp lý an toàn cần kiểm tra gì?",
    shortAnswer: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng.",
    category: "phap-ly",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["so-hong-vinhomes-hoc-mon", "kiem-tra-so-do-truoc-mua-dat", "mua-nha-hinh-thanh-trong-tuong-lai"],
    keywords: ["Đất nền có pháp lý an toàn cần kiểm tra gì", "Đất nền có pháp lý an toàn cần kiểm tra gì 2026", "dat nen phap ly an toan SGS LAND"],
    authorKey: "tran_thi_lan",
    content: "### Đất nền có pháp lý an toàn cần kiểm tra gì?\n\n## Hướng dẫn pháp lý chi tiết\n\nKhi mua BĐS tại Việt Nam, bắt buộc kiểm tra:\n1. Sổ đỏ/sổ hồng chính chủ\n2. Quy hoạch sử dụng đất\n3. Tình trạng thế chấp\n4. Tranh chấp pháp lý\n\n## Chi phí pháp lý 2026\n\n- Phí công chứng: 0,1–0,15% giá trị hợp đồng\n- Thuế trước bạ: 0,5% giá trị căn hộ\n- Lệ phí cấp GCN: 0,5 triệuđ\n- Thời gian làm sổ: 10–15 ngày làm việc\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Sổ hồng ra bao lâu?", a: "10–15 ngày làm việc sau khi nộp hồ sơ đầy đủ." },
    { q: "Có cần công chứng không?", a: "Bắt buộc công chứng hợp đồng mua bán." },
    { q: "SGS LAND hỗ trợ pháp lý không?", a: "Có, có tổ pháp lý miễn phí cho khách mua." }
  ],
    speakableText: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "nguoi-nuoc-ngoai-mua-nha-viet-nam",
    question: "Người nước ngoài mua nhà Việt Nam được không?",
    shortAnswer: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng.",
    category: "phap-ly",
    relatedProjects: [],
    relatedQuestions: ["so-hong-vinhomes-hoc-mon", "kiem-tra-so-do-truoc-mua-dat", "mua-nha-hinh-thanh-trong-tuong-lai"],
    keywords: ["Người nước ngoài mua nhà Việt Nam được không", "Người nước ngoài mua nhà Việt Nam được không 2026", "nguoi nuoc ngoai mua nha viet nam SGS LAND"],
    authorKey: "tran_thi_lan",
    content: "### Người nước ngoài mua nhà Việt Nam được không?\n\n## Hướng dẫn pháp lý chi tiết\n\nKhi mua BĐS tại Việt Nam, bắt buộc kiểm tra:\n1. Sổ đỏ/sổ hồng chính chủ\n2. Quy hoạch sử dụng đất\n3. Tình trạng thế chấp\n4. Tranh chấp pháp lý\n\n## Chi phí pháp lý 2026\n\n- Phí công chứng: 0,1–0,15% giá trị hợp đồng\n- Thuế trước bạ: 0,5% giá trị căn hộ\n- Lệ phí cấp GCN: 0,5 triệuđ\n- Thời gian làm sổ: 10–15 ngày làm việc\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Sổ hồng ra bao lâu?", a: "10–15 ngày làm việc sau khi nộp hồ sơ đầy đủ." },
    { q: "Có cần công chứng không?", a: "Bắt buộc công chứng hợp đồng mua bán." },
    { q: "SGS LAND hỗ trợ pháp lý không?", a: "Có, có tổ pháp lý miễn phí cho khách mua." }
  ],
    speakableText: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "thua-ke-nha-dat-thu-tuc",
    question: "Thừa kế nhà đất thủ tục như thế nào?",
    shortAnswer: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng.",
    category: "phap-ly",
    relatedProjects: [],
    relatedQuestions: ["so-hong-vinhomes-hoc-mon", "kiem-tra-so-do-truoc-mua-dat", "mua-nha-hinh-thanh-trong-tuong-lai"],
    keywords: ["Thừa kế nhà đất thủ tục như thế nào", "Thừa kế nhà đất thủ tục như thế nào 2026", "thua ke nha dat thu tuc SGS LAND"],
    authorKey: "tran_thi_lan",
    content: "### Thừa kế nhà đất thủ tục như thế nào?\n\n## Hướng dẫn pháp lý chi tiết\n\nKhi mua BĐS tại Việt Nam, bắt buộc kiểm tra:\n1. Sổ đỏ/sổ hồng chính chủ\n2. Quy hoạch sử dụng đất\n3. Tình trạng thế chấp\n4. Tranh chấp pháp lý\n\n## Chi phí pháp lý 2026\n\n- Phí công chứng: 0,1–0,15% giá trị hợp đồng\n- Thuế trước bạ: 0,5% giá trị căn hộ\n- Lệ phí cấp GCN: 0,5 triệuđ\n- Thời gian làm sổ: 10–15 ngày làm việc\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Sổ hồng ra bao lâu?", a: "10–15 ngày làm việc sau khi nộp hồ sơ đầy đủ." },
    { q: "Có cần công chứng không?", a: "Bắt buộc công chứng hợp đồng mua bán." },
    { q: "SGS LAND hỗ trợ pháp lý không?", a: "Có, có tổ pháp lý miễn phí cho khách mua." }
  ],
    speakableText: "Cần kiểm tra sổ đỏ, quy hoạch, thế chấp trước khi ký hợp đồng. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vinhomes-hoc-mon-tien-do",
    question: "Tiến độ xây dựng Vinhomes Hóc Môn 2026?",
    shortAnswer: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất.",
    category: "tien-do",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-grand-park-ban-giao", "masteri-cosmo-central-tien-do", "van-phuc-city-tien-do-2026"],
    keywords: ["Tiến độ xây dựng Vinhomes Hóc Môn 2026", "Tiến độ xây dựng Vinhomes Hóc Môn 2026 2026", "vinhomes hoc mon tien do SGS LAND"],
    authorKey: "hoang_duc_minh",
    content: "### Tiến độ xây dựng Vinhomes Hóc Môn 2026?\n\n## Tiến độ cập nhật 06/2026\n\n| Giai đoạn | Dự kiến | Trạng thái |\n|---|---|---|\n| Khởi công | Q2/2024 | ✅ Hoàn tất |\n| Phân kú 1 | Q4/2026 | ⏳ Đang thi công |\n| Phân kú 2 | Q2/2027 | ⏳ Chưa bắt đầu |\n\n## Cam kết tiến độ\n\nChủ đầu tư cam kết tiến độ trong hợp đồng, phạt 0,05%/ngày trễ bàn giao. SGS LAND giám sát tiến độ hàng tuần.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Có bảo lãnh tiến độ không?", a: "Vinhomes, Masterise cam kết trong hợp đồng, phạt 0,05%/ngày trễ." },
    { q: "Bàn giao trễ có được bồi thường?", a: "Có, theo luật kinh doanh BĐS 2024." },
    { q: "Nên mua giai đoạn nào?", a: "Off-plan giá tốt hơn 15–30% so bàn giao." }
  ],
    speakableText: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vinhomes-grand-park-ban-giao",
    question: "Vinhomes Grand Park bao giờ bàn giao?",
    shortAnswer: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất.",
    category: "tien-do",
    relatedProjects: ["vinhomes-grand-park"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-do", "masteri-cosmo-central-tien-do", "van-phuc-city-tien-do-2026"],
    keywords: ["Vinhomes Grand Park bao giờ bàn giao", "Vinhomes Grand Park bao giờ bàn giao 2026", "vinhomes grand park ban giao SGS LAND"],
    authorKey: "hoang_duc_minh",
    content: "### Vinhomes Grand Park bao giờ bàn giao?\n\n## Tiến độ cập nhật 06/2026\n\n| Giai đoạn | Dự kiến | Trạng thái |\n|---|---|---|\n| Khởi công | Q2/2024 | ✅ Hoàn tất |\n| Phân kú 1 | Q4/2026 | ⏳ Đang thi công |\n| Phân kú 2 | Q2/2027 | ⏳ Chưa bắt đầu |\n\n## Cam kết tiến độ\n\nChủ đầu tư cam kết tiến độ trong hợp đồng, phạt 0,05%/ngày trễ bàn giao. SGS LAND giám sát tiến độ hàng tuần.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Có bảo lãnh tiến độ không?", a: "Vinhomes, Masterise cam kết trong hợp đồng, phạt 0,05%/ngày trễ." },
    { q: "Bàn giao trễ có được bồi thường?", a: "Có, theo luật kinh doanh BĐS 2024." },
    { q: "Nên mua giai đoạn nào?", a: "Off-plan giá tốt hơn 15–30% so bàn giao." }
  ],
    speakableText: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "masteri-cosmo-central-tien-do",
    question: "Masteri Cosmo Central tiến độ bao giờ xong?",
    shortAnswer: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất.",
    category: "tien-do",
    relatedProjects: ["masteri-cosmo-central"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-do", "vinhomes-grand-park-ban-giao", "van-phuc-city-tien-do-2026"],
    keywords: ["Masteri Cosmo Central tiến độ bao giờ xong", "Masteri Cosmo Central tiến độ bao giờ xong 2026", "masteri cosmo central tien do SGS LAND"],
    authorKey: "hoang_duc_minh",
    content: "### Masteri Cosmo Central tiến độ bao giờ xong?\n\n## Tiến độ cập nhật 06/2026\n\n| Giai đoạn | Dự kiến | Trạng thái |\n|---|---|---|\n| Khởi công | Q2/2024 | ✅ Hoàn tất |\n| Phân kú 1 | Q4/2026 | ⏳ Đang thi công |\n| Phân kú 2 | Q2/2027 | ⏳ Chưa bắt đầu |\n\n## Cam kết tiến độ\n\nChủ đầu tư cam kết tiến độ trong hợp đồng, phạt 0,05%/ngày trễ bàn giao. SGS LAND giám sát tiến độ hàng tuần.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Có bảo lãnh tiến độ không?", a: "Vinhomes, Masterise cam kết trong hợp đồng, phạt 0,05%/ngày trễ." },
    { q: "Bàn giao trễ có được bồi thường?", a: "Có, theo luật kinh doanh BĐS 2024." },
    { q: "Nên mua giai đoạn nào?", a: "Off-plan giá tốt hơn 15–30% so bàn giao." }
  ],
    speakableText: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "van-phuc-city-tien-do-2026",
    question: "Van Phúc City bao giờ hoàn thành?",
    shortAnswer: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất.",
    category: "tien-do",
    relatedProjects: ["van-phuc-city"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-do", "vinhomes-grand-park-ban-giao", "masteri-cosmo-central-tien-do"],
    keywords: ["Van Phúc City bao giờ hoàn thành", "Van Phúc City bao giờ hoàn thành 2026", "van phuc city tien do 2026 SGS LAND"],
    authorKey: "hoang_duc_minh",
    content: "### Van Phúc City bao giờ hoàn thành?\n\n## Tiến độ cập nhật 06/2026\n\n| Giai đoạn | Dự kiến | Trạng thái |\n|---|---|---|\n| Khởi công | Q2/2024 | ✅ Hoàn tất |\n| Phân kú 1 | Q4/2026 | ⏳ Đang thi công |\n| Phân kú 2 | Q2/2027 | ⏳ Chưa bắt đầu |\n\n## Cam kết tiến độ\n\nChủ đầu tư cam kết tiến độ trong hợp đồng, phạt 0,05%/ngày trễ bàn giao. SGS LAND giám sát tiến độ hàng tuần.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Có bảo lãnh tiến độ không?", a: "Vinhomes, Masterise cam kết trong hợp đồng, phạt 0,05%/ngày trễ." },
    { q: "Bàn giao trễ có được bồi thường?", a: "Có, theo luật kinh doanh BĐS 2024." },
    { q: "Nên mua giai đoạn nào?", a: "Off-plan giá tốt hơn 15–30% so bàn giao." }
  ],
    speakableText: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "metro-hoc-mon-khi-nao-xong",
    question: "Metro Hóc Môn bao giờ hoạt động?",
    shortAnswer: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất.",
    category: "tien-do",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-do", "vinhomes-grand-park-ban-giao", "masteri-cosmo-central-tien-do"],
    keywords: ["Metro Hóc Môn bao giờ hoạt động", "Metro Hóc Môn bao giờ hoạt động 2026", "metro hoc mon khi nao xong SGS LAND"],
    authorKey: "hoang_duc_minh",
    content: "### Metro Hóc Môn bao giờ hoạt động?\n\n## Tiến độ cập nhật 06/2026\n\n| Giai đoạn | Dự kiến | Trạng thái |\n|---|---|---|\n| Khởi công | Q2/2024 | ✅ Hoàn tất |\n| Phân kú 1 | Q4/2026 | ⏳ Đang thi công |\n| Phân kú 2 | Q2/2027 | ⏳ Chưa bắt đầu |\n\n## Cam kết tiến độ\n\nChủ đầu tư cam kết tiến độ trong hợp đồng, phạt 0,05%/ngày trễ bàn giao. SGS LAND giám sát tiến độ hàng tuần.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Có bảo lãnh tiến độ không?", a: "Vinhomes, Masterise cam kết trong hợp đồng, phạt 0,05%/ngày trễ." },
    { q: "Bàn giao trễ có được bồi thường?", a: "Có, theo luật kinh doanh BĐS 2024." },
    { q: "Nên mua giai đoạn nào?", a: "Off-plan giá tốt hơn 15–30% so bàn giao." }
  ],
    speakableText: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vanh-dai-3-hoc-mon-tien-do",
    question: "Vành đai 3 qua Hóc Môn bao giờ xong?",
    shortAnswer: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất.",
    category: "tien-do",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-do", "vinhomes-grand-park-ban-giao", "masteri-cosmo-central-tien-do"],
    keywords: ["Vành đai 3 qua Hóc Môn bao giờ xong", "Vành đai 3 qua Hóc Môn bao giờ xong 2026", "vanh dai 3 hoc mon tien do SGS LAND"],
    authorKey: "hoang_duc_minh",
    content: "### Vành đai 3 qua Hóc Môn bao giờ xong?\n\n## Tiến độ cập nhật 06/2026\n\n| Giai đoạn | Dự kiến | Trạng thái |\n|---|---|---|\n| Khởi công | Q2/2024 | ✅ Hoàn tất |\n| Phân kú 1 | Q4/2026 | ⏳ Đang thi công |\n| Phân kú 2 | Q2/2027 | ⏳ Chưa bắt đầu |\n\n## Cam kết tiến độ\n\nChủ đầu tư cam kết tiến độ trong hợp đồng, phạt 0,05%/ngày trễ bàn giao. SGS LAND giám sát tiến độ hàng tuần.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Có bảo lãnh tiến độ không?", a: "Vinhomes, Masterise cam kết trong hợp đồng, phạt 0,05%/ngày trễ." },
    { q: "Bàn giao trễ có được bồi thường?", a: "Có, theo luật kinh doanh BĐS 2024." },
    { q: "Nên mua giai đoạn nào?", a: "Off-plan giá tốt hơn 15–30% so bàn giao." }
  ],
    speakableText: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "thu-thiem-quy-hoach-2030",
    question: "Thủ Thiêm quy hoạch 2030 như thế nào?",
    shortAnswer: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất.",
    category: "tien-do",
    relatedProjects: ["masteri-cosmo-central"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-do", "vinhomes-grand-park-ban-giao", "masteri-cosmo-central-tien-do"],
    keywords: ["Thủ Thiêm quy hoạch 2030 như thế nào", "Thủ Thiêm quy hoạch 2030 như thế nào 2026", "thu thiem quy hoach 2030 SGS LAND"],
    authorKey: "hoang_duc_minh",
    content: "### Thủ Thiêm quy hoạch 2030 như thế nào?\n\n## Tiến độ cập nhật 06/2026\n\n| Giai đoạn | Dự kiến | Trạng thái |\n|---|---|---|\n| Khởi công | Q2/2024 | ✅ Hoàn tất |\n| Phân kú 1 | Q4/2026 | ⏳ Đang thi công |\n| Phân kú 2 | Q2/2027 | ⏳ Chưa bắt đầu |\n\n## Cam kết tiến độ\n\nChủ đầu tư cam kết tiến độ trong hợp đồng, phạt 0,05%/ngày trễ bàn giao. SGS LAND giám sát tiến độ hàng tuần.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Có bảo lãnh tiến độ không?", a: "Vinhomes, Masterise cam kết trong hợp đồng, phạt 0,05%/ngày trễ." },
    { q: "Bàn giao trễ có được bồi thường?", a: "Có, theo luật kinh doanh BĐS 2024." },
    { q: "Nên mua giai đoạn nào?", a: "Off-plan giá tốt hơn 15–30% so bàn giao." }
  ],
    speakableText: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "quan-9-thu-duc-phat-trien",
    question: "Quận 9 - TP Thủ Đức phát triển 2026?",
    shortAnswer: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất.",
    category: "tien-do",
    relatedProjects: ["vinhomes-grand-park"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-do", "vinhomes-grand-park-ban-giao", "masteri-cosmo-central-tien-do"],
    keywords: ["Quận 9 - TP Thủ Đức phát triển 2026", "Quận 9 - TP Thủ Đức phát triển 2026 2026", "quan 9 thu duc phat trien SGS LAND"],
    authorKey: "hoang_duc_minh",
    content: "### Quận 9 - TP Thủ Đức phát triển 2026?\n\n## Tiến độ cập nhật 06/2026\n\n| Giai đoạn | Dự kiến | Trạng thái |\n|---|---|---|\n| Khởi công | Q2/2024 | ✅ Hoàn tất |\n| Phân kú 1 | Q4/2026 | ⏳ Đang thi công |\n| Phân kú 2 | Q2/2027 | ⏳ Chưa bắt đầu |\n\n## Cam kết tiến độ\n\nChủ đầu tư cam kết tiến độ trong hợp đồng, phạt 0,05%/ngày trễ bàn giao. SGS LAND giám sát tiến độ hàng tuần.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Có bảo lãnh tiến độ không?", a: "Vinhomes, Masterise cam kết trong hợp đồng, phạt 0,05%/ngày trễ." },
    { q: "Bàn giao trễ có được bồi thường?", a: "Có, theo luật kinh doanh BĐS 2024." },
    { q: "Nên mua giai đoạn nào?", a: "Off-plan giá tốt hơn 15–30% so bàn giao." }
  ],
    speakableText: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "binh-duong-ha-tang-2026",
    question: "Hạ tầng Bình Dương 2026 có gì mới?",
    shortAnswer: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất.",
    category: "tien-do",
    relatedProjects: ["van-phuc-city"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-do", "vinhomes-grand-park-ban-giao", "masteri-cosmo-central-tien-do"],
    keywords: ["Hạ tầng Bình Dương 2026 có gì mới", "Hạ tầng Bình Dương 2026 có gì mới 2026", "binh duong ha tang 2026 SGS LAND"],
    authorKey: "hoang_duc_minh",
    content: "### Hạ tầng Bình Dương 2026 có gì mới?\n\n## Tiến độ cập nhật 06/2026\n\n| Giai đoạn | Dự kiến | Trạng thái |\n|---|---|---|\n| Khởi công | Q2/2024 | ✅ Hoàn tất |\n| Phân kú 1 | Q4/2026 | ⏳ Đang thi công |\n| Phân kú 2 | Q2/2027 | ⏳ Chưa bắt đầu |\n\n## Cam kết tiến độ\n\nChủ đầu tư cam kết tiến độ trong hợp đồng, phạt 0,05%/ngày trễ bàn giao. SGS LAND giám sát tiến độ hàng tuần.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Có bảo lãnh tiến độ không?", a: "Vinhomes, Masterise cam kết trong hợp đồng, phạt 0,05%/ngày trễ." },
    { q: "Bàn giao trễ có được bồi thường?", a: "Có, theo luật kinh doanh BĐS 2024." },
    { q: "Nên mua giai đoạn nào?", a: "Off-plan giá tốt hơn 15–30% so bàn giao." }
  ],
    speakableText: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "sun-thu-thiem-tien-do",
    question: "Sun Thủ Thiêm tiến độ 2026?",
    shortAnswer: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất.",
    category: "tien-do",
    relatedProjects: ["masteri-cosmo-central"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-do", "vinhomes-grand-park-ban-giao", "masteri-cosmo-central-tien-do"],
    keywords: ["Sun Thủ Thiêm tiến độ 2026", "Sun Thủ Thiêm tiến độ 2026 2026", "sun thu thiem tien do SGS LAND"],
    authorKey: "hoang_duc_minh",
    content: "### Sun Thủ Thiêm tiến độ 2026?\n\n## Tiến độ cập nhật 06/2026\n\n| Giai đoạn | Dự kiến | Trạng thái |\n|---|---|---|\n| Khởi công | Q2/2024 | ✅ Hoàn tất |\n| Phân kú 1 | Q4/2026 | ⏳ Đang thi công |\n| Phân kú 2 | Q2/2027 | ⏳ Chưa bắt đầu |\n\n## Cam kết tiến độ\n\nChủ đầu tư cam kết tiến độ trong hợp đồng, phạt 0,05%/ngày trễ bàn giao. SGS LAND giám sát tiến độ hàng tuần.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Có bảo lãnh tiến độ không?", a: "Vinhomes, Masterise cam kết trong hợp đồng, phạt 0,05%/ngày trễ." },
    { q: "Bàn giao trễ có được bồi thường?", a: "Có, theo luật kinh doanh BĐS 2024." },
    { q: "Nên mua giai đoạn nào?", a: "Off-plan giá tốt hơn 15–30% so bàn giao." }
  ],
    speakableText: "Tiến độ cập nhật hàng ngày. Liên hệ SGS LAND để nhận báo cáo tiến độ mới nhất. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vinhomes-hoc-mon-tien-ich",
    question: "Vinhomes Hóc Môn có tiện ích gì?",
    shortAnswer: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7.",
    category: "tien-ich",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-grand-park-cong-vien", "truong-hoc-benhvien-vinhomes", "van-phuc-city-tien-ich"],
    keywords: ["Vinhomes Hóc Môn có tiện ích gì", "Vinhomes Hóc Môn có tiện ích gì 2026", "vinhomes hoc mon tien ich SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Vinhomes Hóc Môn có tiện ích gì?\n\n## Tiện ích nội khu đẳng cấp\n\n- **Giáo dục**: Vinschool mầm non, tiểu học, THCS — top 10 trường tư TP.HCM\n- **Y tế**: Bệnh viện Vinmec cấp cứu 24/7\n- **Thương mại**: Vincom Mega Mall, Vinmart, nhà hàng cao cấp\n- **Vui chơi**: Công viên chủ đề, bể bơi vô cực, gym, spa\n- **An ninh**: Bảo vệ 24/7, camera AI, thẻ từ cấm cảnh\n\n## Phí dịch vụ hàng tháng\n\nPhí quản lý: 10.000–15.000 đ/m²/tháng. Tức căn 80m² tốn 800k–1,2 triệu/tháng.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tiện ích có mất phí không?", a: "Một số tiện ích miễn phí, một số tính theo phí dịch vụ." },
    { q: "Vinschool có tốt không?", a: "Top 10 trường tư tốt nhất TP.HCM, học phí 60–120 triệu/năm." },
    { q: "Vinmec có cấp cứu 24/7 không?", a: "Có, bệnh viện 24/7 cấp cứu trong vòng 15 phút." }
  ],
    speakableText: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "vinhomes-grand-park-cong-vien",
    question: "Công viên Vinhomes Grand Park có gì?",
    shortAnswer: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7.",
    category: "tien-ich",
    relatedProjects: ["vinhomes-grand-park"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-ich", "truong-hoc-benhvien-vinhomes", "van-phuc-city-tien-ich"],
    keywords: ["Công viên Vinhomes Grand Park có gì", "Công viên Vinhomes Grand Park có gì 2026", "vinhomes grand park cong vien SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Công viên Vinhomes Grand Park có gì?\n\n## Tiện ích nội khu đẳng cấp\n\n- **Giáo dục**: Vinschool mầm non, tiểu học, THCS — top 10 trường tư TP.HCM\n- **Y tế**: Bệnh viện Vinmec cấp cứu 24/7\n- **Thương mại**: Vincom Mega Mall, Vinmart, nhà hàng cao cấp\n- **Vui chơi**: Công viên chủ đề, bể bơi vô cực, gym, spa\n- **An ninh**: Bảo vệ 24/7, camera AI, thẻ từ cấm cảnh\n\n## Phí dịch vụ hàng tháng\n\nPhí quản lý: 10.000–15.000 đ/m²/tháng. Tức căn 80m² tốn 800k–1,2 triệu/tháng.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tiện ích có mất phí không?", a: "Một số tiện ích miễn phí, một số tính theo phí dịch vụ." },
    { q: "Vinschool có tốt không?", a: "Top 10 trường tư tốt nhất TP.HCM, học phí 60–120 triệu/năm." },
    { q: "Vinmec có cấp cứu 24/7 không?", a: "Có, bệnh viện 24/7 cấp cứu trong vòng 15 phút." }
  ],
    speakableText: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "truong-hoc-benhvien-vinhomes",
    question: "Trường học bệnh viện Vinhomes có đáng tin?",
    shortAnswer: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7.",
    category: "tien-ich",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-ich", "vinhomes-grand-park-cong-vien", "van-phuc-city-tien-ich"],
    keywords: ["Trường học bệnh viện Vinhomes có đáng tin", "Trường học bệnh viện Vinhomes có đáng tin 2026", "truong hoc benhvien vinhomes SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Trường học bệnh viện Vinhomes có đáng tin?\n\n## Tiện ích nội khu đẳng cấp\n\n- **Giáo dục**: Vinschool mầm non, tiểu học, THCS — top 10 trường tư TP.HCM\n- **Y tế**: Bệnh viện Vinmec cấp cứu 24/7\n- **Thương mại**: Vincom Mega Mall, Vinmart, nhà hàng cao cấp\n- **Vui chơi**: Công viên chủ đề, bể bơi vô cực, gym, spa\n- **An ninh**: Bảo vệ 24/7, camera AI, thẻ từ cấm cảnh\n\n## Phí dịch vụ hàng tháng\n\nPhí quản lý: 10.000–15.000 đ/m²/tháng. Tức căn 80m² tốn 800k–1,2 triệu/tháng.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tiện ích có mất phí không?", a: "Một số tiện ích miễn phí, một số tính theo phí dịch vụ." },
    { q: "Vinschool có tốt không?", a: "Top 10 trường tư tốt nhất TP.HCM, học phí 60–120 triệu/năm." },
    { q: "Vinmec có cấp cứu 24/7 không?", a: "Có, bệnh viện 24/7 cấp cứu trong vòng 15 phút." }
  ],
    speakableText: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "van-phuc-city-tien-ich",
    question: "Van Phúc City tiện ích nội khu có những gì?",
    shortAnswer: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7.",
    category: "tien-ich",
    relatedProjects: ["van-phuc-city"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-ich", "vinhomes-grand-park-cong-vien", "truong-hoc-benhvien-vinhomes"],
    keywords: ["Van Phúc City tiện ích nội khu có những gì", "Van Phúc City tiện ích nội khu có những gì 2026", "van phuc city tien ich SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Van Phúc City tiện ích nội khu có những gì?\n\n## Tiện ích nội khu đẳng cấp\n\n- **Giáo dục**: Vinschool mầm non, tiểu học, THCS — top 10 trường tư TP.HCM\n- **Y tế**: Bệnh viện Vinmec cấp cứu 24/7\n- **Thương mại**: Vincom Mega Mall, Vinmart, nhà hàng cao cấp\n- **Vui chơi**: Công viên chủ đề, bể bơi vô cực, gym, spa\n- **An ninh**: Bảo vệ 24/7, camera AI, thẻ từ cấm cảnh\n\n## Phí dịch vụ hàng tháng\n\nPhí quản lý: 10.000–15.000 đ/m²/tháng. Tức căn 80m² tốn 800k–1,2 triệu/tháng.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tiện ích có mất phí không?", a: "Một số tiện ích miễn phí, một số tính theo phí dịch vụ." },
    { q: "Vinschool có tốt không?", a: "Top 10 trường tư tốt nhất TP.HCM, học phí 60–120 triệu/năm." },
    { q: "Vinmec có cấp cứu 24/7 không?", a: "Có, bệnh viện 24/7 cấp cứu trong vòng 15 phút." }
  ],
    speakableText: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "masteri-ho-boi-gym",
    question: "Masteri Cosmo Central có hồ bơi gym cao cấp?",
    shortAnswer: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7.",
    category: "tien-ich",
    relatedProjects: ["masteri-cosmo-central"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-ich", "vinhomes-grand-park-cong-vien", "truong-hoc-benhvien-vinhomes"],
    keywords: ["Masteri Cosmo Central có hồ bơi gym cao cấp", "Masteri Cosmo Central có hồ bơi gym cao cấp 2026", "masteri ho boi gym SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Masteri Cosmo Central có hồ bơi gym cao cấp?\n\n## Tiện ích nội khu đẳng cấp\n\n- **Giáo dục**: Vinschool mầm non, tiểu học, THCS — top 10 trường tư TP.HCM\n- **Y tế**: Bệnh viện Vinmec cấp cứu 24/7\n- **Thương mại**: Vincom Mega Mall, Vinmart, nhà hàng cao cấp\n- **Vui chơi**: Công viên chủ đề, bể bơi vô cực, gym, spa\n- **An ninh**: Bảo vệ 24/7, camera AI, thẻ từ cấm cảnh\n\n## Phí dịch vụ hàng tháng\n\nPhí quản lý: 10.000–15.000 đ/m²/tháng. Tức căn 80m² tốn 800k–1,2 triệu/tháng.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tiện ích có mất phí không?", a: "Một số tiện ích miễn phí, một số tính theo phí dịch vụ." },
    { q: "Vinschool có tốt không?", a: "Top 10 trường tư tốt nhất TP.HCM, học phí 60–120 triệu/năm." },
    { q: "Vinmec có cấp cứu 24/7 không?", a: "Có, bệnh viện 24/7 cấp cứu trong vòng 15 phút." }
  ],
    speakableText: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "mua-nha-gan-truong-hoc-hcm",
    question: "Mua nhà gần trường học tốt nhất TP.HCM?",
    shortAnswer: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7.",
    category: "tien-ich",
    relatedProjects: ["vinhomes-grand-park"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-ich", "vinhomes-grand-park-cong-vien", "truong-hoc-benhvien-vinhomes"],
    keywords: ["Mua nhà gần trường học tốt nhất TP.HCM", "Mua nhà gần trường học tốt nhất TP.HCM 2026", "mua nha gan truong hoc hcm SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Mua nhà gần trường học tốt nhất TP.HCM?\n\n## Tiện ích nội khu đẳng cấp\n\n- **Giáo dục**: Vinschool mầm non, tiểu học, THCS — top 10 trường tư TP.HCM\n- **Y tế**: Bệnh viện Vinmec cấp cứu 24/7\n- **Thương mại**: Vincom Mega Mall, Vinmart, nhà hàng cao cấp\n- **Vui chơi**: Công viên chủ đề, bể bơi vô cực, gym, spa\n- **An ninh**: Bảo vệ 24/7, camera AI, thẻ từ cấm cảnh\n\n## Phí dịch vụ hàng tháng\n\nPhí quản lý: 10.000–15.000 đ/m²/tháng. Tức căn 80m² tốn 800k–1,2 triệu/tháng.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tiện ích có mất phí không?", a: "Một số tiện ích miễn phí, một số tính theo phí dịch vụ." },
    { q: "Vinschool có tốt không?", a: "Top 10 trường tư tốt nhất TP.HCM, học phí 60–120 triệu/năm." },
    { q: "Vinmec có cấp cứu 24/7 không?", a: "Có, bệnh viện 24/7 cấp cứu trong vòng 15 phút." }
  ],
    speakableText: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "an-ninh-khu-do-thi-vinhomes",
    question: "An ninh khu đô thị Vinhomes tốt không?",
    shortAnswer: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7.",
    category: "tien-ich",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-ich", "vinhomes-grand-park-cong-vien", "truong-hoc-benhvien-vinhomes"],
    keywords: ["An ninh khu đô thị Vinhomes tốt không", "An ninh khu đô thị Vinhomes tốt không 2026", "an ninh khu do thi vinhomes SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### An ninh khu đô thị Vinhomes tốt không?\n\n## Tiện ích nội khu đẳng cấp\n\n- **Giáo dục**: Vinschool mầm non, tiểu học, THCS — top 10 trường tư TP.HCM\n- **Y tế**: Bệnh viện Vinmec cấp cứu 24/7\n- **Thương mại**: Vincom Mega Mall, Vinmart, nhà hàng cao cấp\n- **Vui chơi**: Công viên chủ đề, bể bơi vô cực, gym, spa\n- **An ninh**: Bảo vệ 24/7, camera AI, thẻ từ cấm cảnh\n\n## Phí dịch vụ hàng tháng\n\nPhí quản lý: 10.000–15.000 đ/m²/tháng. Tức căn 80m² tốn 800k–1,2 triệu/tháng.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tiện ích có mất phí không?", a: "Một số tiện ích miễn phí, một số tính theo phí dịch vụ." },
    { q: "Vinschool có tốt không?", a: "Top 10 trường tư tốt nhất TP.HCM, học phí 60–120 triệu/năm." },
    { q: "Vinmec có cấp cứu 24/7 không?", a: "Có, bệnh viện 24/7 cấp cứu trong vòng 15 phút." }
  ],
    speakableText: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "phi-dich-vu-chung-cu-vinhomes",
    question: "Phí dịch vụ chung cư Vinhomes bao nhiêu/tháng?",
    shortAnswer: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7.",
    category: "tien-ich",
    relatedProjects: ["vinhomes-grand-park"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-ich", "vinhomes-grand-park-cong-vien", "truong-hoc-benhvien-vinhomes"],
    keywords: ["Phí dịch vụ chung cư Vinhomes bao nhiêu/tháng", "Phí dịch vụ chung cư Vinhomes bao nhiêu/tháng 2026", "phi dich vu chung cu vinhomes SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Phí dịch vụ chung cư Vinhomes bao nhiêu/tháng?\n\n## Tiện ích nội khu đẳng cấp\n\n- **Giáo dục**: Vinschool mầm non, tiểu học, THCS — top 10 trường tư TP.HCM\n- **Y tế**: Bệnh viện Vinmec cấp cứu 24/7\n- **Thương mại**: Vincom Mega Mall, Vinmart, nhà hàng cao cấp\n- **Vui chơi**: Công viên chủ đề, bể bơi vô cực, gym, spa\n- **An ninh**: Bảo vệ 24/7, camera AI, thẻ từ cấm cảnh\n\n## Phí dịch vụ hàng tháng\n\nPhí quản lý: 10.000–15.000 đ/m²/tháng. Tức căn 80m² tốn 800k–1,2 triệu/tháng.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tiện ích có mất phí không?", a: "Một số tiện ích miễn phí, một số tính theo phí dịch vụ." },
    { q: "Vinschool có tốt không?", a: "Top 10 trường tư tốt nhất TP.HCM, học phí 60–120 triệu/năm." },
    { q: "Vinmec có cấp cứu 24/7 không?", a: "Có, bệnh viện 24/7 cấp cứu trong vòng 15 phút." }
  ],
    speakableText: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "khu-do-thi-co-cho-dau-xe",
    question: "Khu đô thị Vinhomes có chỗ đậu xe?",
    shortAnswer: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7.",
    category: "tien-ich",
    relatedProjects: ["vinhomes-hoc-mon"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-ich", "vinhomes-grand-park-cong-vien", "truong-hoc-benhvien-vinhomes"],
    keywords: ["Khu đô thị Vinhomes có chỗ đậu xe", "Khu đô thị Vinhomes có chỗ đậu xe 2026", "khu do thi co cho dau xe SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Khu đô thị Vinhomes có chỗ đậu xe?\n\n## Tiện ích nội khu đẳng cấp\n\n- **Giáo dục**: Vinschool mầm non, tiểu học, THCS — top 10 trường tư TP.HCM\n- **Y tế**: Bệnh viện Vinmec cấp cứu 24/7\n- **Thương mại**: Vincom Mega Mall, Vinmart, nhà hàng cao cấp\n- **Vui chơi**: Công viên chủ đề, bể bơi vô cực, gym, spa\n- **An ninh**: Bảo vệ 24/7, camera AI, thẻ từ cấm cảnh\n\n## Phí dịch vụ hàng tháng\n\nPhí quản lý: 10.000–15.000 đ/m²/tháng. Tức căn 80m² tốn 800k–1,2 triệu/tháng.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tiện ích có mất phí không?", a: "Một số tiện ích miễn phí, một số tính theo phí dịch vụ." },
    { q: "Vinschool có tốt không?", a: "Top 10 trường tư tốt nhất TP.HCM, học phí 60–120 triệu/năm." },
    { q: "Vinmec có cấp cứu 24/7 không?", a: "Có, bệnh viện 24/7 cấp cứu trong vòng 15 phút." }
  ],
    speakableText: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7. Liên hệ SGS LAND 1800 6665.",
  },
  {
    slug: "pet-friendly-vinhomes",
    question: "Vinhomes có cho nuôi thú cưng không?",
    shortAnswer: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7.",
    category: "tien-ich",
    relatedProjects: ["vinhomes-grand-park"],
    relatedQuestions: ["vinhomes-hoc-mon-tien-ich", "vinhomes-grand-park-cong-vien", "truong-hoc-benhvien-vinhomes"],
    keywords: ["Vinhomes có cho nuôi thú cưng không", "Vinhomes có cho nuôi thú cưng không 2026", "pet friendly vinhomes SGS LAND"],
    authorKey: "nguyen_minh_duc",
    content: "### Vinhomes có cho nuôi thú cưng không?\n\n## Tiện ích nội khu đẳng cấp\n\n- **Giáo dục**: Vinschool mầm non, tiểu học, THCS — top 10 trường tư TP.HCM\n- **Y tế**: Bệnh viện Vinmec cấp cứu 24/7\n- **Thương mại**: Vincom Mega Mall, Vinmart, nhà hàng cao cấp\n- **Vui chơi**: Công viên chủ đề, bể bơi vô cực, gym, spa\n- **An ninh**: Bảo vệ 24/7, camera AI, thẻ từ cấm cảnh\n\n## Phí dịch vụ hàng tháng\n\nPhí quản lý: 10.000–15.000 đ/m²/tháng. Tức căn 80m² tốn 800k–1,2 triệu/tháng.\n\nHãy liên hệ SGS LAND hotline **1800 6665** để nhận tư vấn miễn phí.",
    faqItems: [
    { q: "Tiện ích có mất phí không?", a: "Một số tiện ích miễn phí, một số tính theo phí dịch vụ." },
    { q: "Vinschool có tốt không?", a: "Top 10 trường tư tốt nhất TP.HCM, học phí 60–120 triệu/năm." },
    { q: "Vinmec có cấp cứu 24/7 không?", a: "Có, bệnh viện 24/7 cấp cứu trong vòng 15 phút." }
  ],
    speakableText: "Tiện ích 5 sao: trường học, bệnh viện, công viên, bể bơi, gym, bảo vệ 24/7. Liên hệ SGS LAND 1800 6665.",
  },
];

export const FAQ_MAP = new Map(FAQ_DATA.map(f => [f.slug, f]));
export const FAQ_SLUGS = FAQ_DATA.map(f => f.slug);

export function getFaqsByCategory(cat: string): FaqEntry[] {
  return FAQ_DATA.filter(f => f.category === cat);
}
