import fs from 'node:fs';
const F = 'pages/Projects.tsx';
let s = fs.readFileSync(F, 'utf8');
const out = [];
const rep = (n, a, b) => { if (!s.includes(a)) { out.push('FAIL ' + n); return; } s = s.replace(a, () => b); out.push('OK ' + n); };
rep('card min width', 'sm:grid-cols-[repeat(auto-fill,minmax(300px,1fr))]', 'sm:grid-cols-[repeat(auto-fill,minmax(340px,1fr))]');
rep('code header', "<div className=\"w-24 shrink-0\">{t('project.listing_col_code')}</div>", "<div className=\"w-28 shrink-0\">{t('project.listing_col_code')}</div>");
rep('code cell', '<div className="w-24 shrink-0">\n                                            <span className="text-xs font-medium tabular-nums', '<div className="w-28 shrink-0 pr-2">\n                                            <span className="text-xs font-medium tabular-nums');
fs.writeFileSync(F, s);
console.log(out.join('\n'));
