/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './*.tsx',
    './*.ts',
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './services/**/*.{ts,tsx}',
    './utils/**/*.{ts,tsx}',
    './config/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Be Vietnam Pro"', 'system-ui', 'sans-serif'],
        serif: ['"Fraunces"', 'Georgia', 'serif'],
        display: ['"Fraunces"', 'Georgia', 'serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        // Semantic scale. Legacy aliases remain available during migration.
        '3xs': ['10px', { lineHeight: '14px' }],
        '2xs': ['11px', { lineHeight: '16px' }],
        'xs2': ['12px', { lineHeight: '16px' }],
        'xs3': ['13px', { lineHeight: '18px' }],
        'xs':   ['13px', { lineHeight: '18px' }],
        'sm':   ['14px', { lineHeight: '20px' }],
        'base': ['16px', { lineHeight: '24px' }],
        'lg':   ['18px', { lineHeight: '28px' }],
        'xl':   ['20px', { lineHeight: '28px' }],
        '2xl':  ['24px', { lineHeight: '32px' }],
        '3xl':  ['30px', { lineHeight: '38px' }],
        '4xl':  ['36px', { lineHeight: '44px' }],
        '5xl':  ['48px', { lineHeight: '56px' }],
        '6xl':  ['60px', { lineHeight: '68px' }],
        'ui-display': ['clamp(2rem, 4vw, 3.75rem)', { lineHeight: '1.05' }],
        'ui-heading': ['clamp(1.5rem, 2.4vw, 2.25rem)', { lineHeight: '1.15' }],
        'ui-body': ['1rem', { lineHeight: '1.5' }],
        'ui-label': ['0.875rem', { lineHeight: '1.4' }],
        'ui-kicker': ['0.75rem', { lineHeight: '1.35' }],
        'ui-caption': ['0.8125rem', { lineHeight: '1.4' }],
      },
      colors: {
        // === SGS LAND DESIGN TOKENS (maps to CSS vars) ===
        'sgs-bg':            'var(--sgs-bg)',
        'sgs-surface':       'var(--sgs-surface)',
        'sgs-primary':       'var(--sgs-primary)',
        'sgs-primary-deep':  'var(--sgs-primary-deep)',
        'sgs-accent':        'var(--sgs-accent)',
        'sgs-accent-text':   'var(--sgs-accent-text)',
        'sgs-text':          'var(--sgs-text)',
        'sgs-text-muted':    'var(--sgs-text-muted)',
        'sgs-text-heading':  'var(--sgs-text-heading)',
        'sgs-verified':      'var(--sgs-verified)',
        'sgs-hero-deep':     'var(--sgs-hero-deep)',
        'sgs-champagne':     'var(--sgs-champagne)',
        'sgs-on-dark-muted': 'var(--sgs-on-dark-muted)',
        'sgs-subtle-bg':     'var(--sgs-subtle-bg)',
        'sgs-border':        'var(--sgs-border)',
        surface:          'var(--bg-surface)',
        'surface-elevated': 'var(--bg-elevated)',
        'app-bg':         'var(--bg-app)',
        sidebar:          'var(--bg-sidebar)',
        input:            'var(--bg-input)',
        primary: {
          DEFAULT: 'var(--primary-600)',
          600:     'var(--primary-600)',
          hover:   'var(--primary-hover)',
          subtle:  'var(--primary-subtle)',
        },
        'text-primary':   'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary':  'var(--text-tertiary)',
        'text-muted':     'var(--text-muted)',
        'text-inverse':   'var(--text-inverse)',
        'status-success': 'var(--color-success)',
        'status-warning': 'var(--color-warning)',
        'status-danger':  'var(--color-danger)',
        'status-info':    'var(--color-info)',
        'glass':          'var(--glass-surface)',
        'glass-border':   'var(--glass-border)',
        'border-default': 'var(--border-default)',
        'border-strong':  'var(--border-strong)',
      },
      boxShadow: {
        'token-sm': 'var(--shadow-sm)',
        'token-md': 'var(--shadow-md)',
        'token-lg': 'var(--shadow-lg)',
      },
      animation: {
        'scale-up': 'scaleUp 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-in-right': 'slideInRight 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'shimmer': 'shimmer 1.4s ease-in-out infinite',
      },
      keyframes: {
        scaleUp: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
      },
    },
  },
  plugins: [],
};