import { ROUTES } from './routes';

export const PAGE_LABELS: Record<string, string> = {
  [ROUTES.DASHBOARD]: 'Bảng Điều Khiển',
  [ROUTES.LEADS]: 'Khách Hàng Tiềm Năng',
  [ROUTES.CONTRACTS]: 'Hợp Đồng',
  [ROUTES.INVENTORY]: 'Kho Bất Động Sản',
  [ROUTES.LISTING]: 'Chi Tiết Bất Động Sản',
  [ROUTES.FAVORITES]: 'Danh Sách Yêu Thích',
  [ROUTES.INBOX]: 'Hộp Thư',
  [ROUTES.REPORTS]: 'Báo Cáo',
  [ROUTES.APPROVALS]: 'Phê Duyệt',
  [ROUTES.ROUTING_RULES]: 'Quy Tắc Phân Phối',
  [ROUTES.SEQUENCES]: 'Chuỗi Tự Động',
  [ROUTES.SCORING_RULES]: 'Quy Tắc Chấm Điểm',
  [ROUTES.KNOWLEDGE]: 'Cơ Sở Kiến Thức',
  [ROUTES.SYSTEM]: 'Trạng Thái Hệ Thống',
  [ROUTES.ADMIN_USERS]: 'Quản Lý Người Dùng',
  [ROUTES.ENTERPRISE_SETTINGS]: 'Cài Đặt Doanh Nghiệp',
  [ROUTES.BILLING]: 'Thanh Toán',
  [ROUTES.MARKETPLACE]: 'Marketplace',
  [ROUTES.DATA_PLATFORM]: 'Nền Tảng Dữ Liệu',
  [ROUTES.SECURITY]: 'Bảo Mật & Tuân Thủ',
  [ROUTES.AI_GOVERNANCE]: 'Quản Trị AI',
  [ROUTES.SEO_MANAGER]: 'Quản Lý SEO',
  [ROUTES.PROFILE]: 'Hồ Sơ Cá Nhân',
  [ROUTES.MOBILE_APP]: 'Ứng Dụng Di Động',
};
