
export const ROUTES = {
    LOGIN: 'login',
    PUBLIC_PREFIX: 'p',
    DEFAULT_PRIVATE: 'dashboard',
    
    // Public Pages
    LANDING: 'home', 
    SEARCH: 'marketplace',  // Matched with footer and other navigation
    AI_VALUATION: 'ai-valuation',
  AI_ADVISOR: 'ai-advisor',   
    CRM_SOLUTION: 'crm-platform',   
    ABOUT: 'about-us',
    NEWS: 'news',
    CONTACT: 'contact',
    CAREERS: 'careers',
    HELP_CENTER: 'help-center',
    USER_GUIDE: 'huong-dan-su-dung',
    API_DOCS: 'developers',
    STATUS_PUBLIC: 'status',
    LIVE_CHAT: 'livechat',
    KY_GUI: 'ky-gui-bat-dong-san',
    BANK_RATES: 'lai-suat-ngan-hang',

    // SEO Landing Pages — Local & Project
    BDS_DONG_NAI: 'bat-dong-san-dong-nai',
    BDS_LONG_THANH: 'bat-dong-san-long-thanh',
    BDS_THU_DUC: 'bat-dong-san-thu-duc',
    BDS_BINH_DUONG: 'bat-dong-san-binh-duong',
    BDS_QUAN_7: 'bat-dong-san-quan-7',
    BDS_PHU_NHUAN: 'bat-dong-san-phu-nhuan',
    BDS_BINH_CHANH: 'bat-dong-san-binh-chanh',
    BDS_BINH_THANH: 'bat-dong-san-binh-thanh',
    BDS_LONG_AN: 'bat-dong-san-long-an',
    DAU_TU_BDS: 'dau-tu-bat-dong-san',
    PHAP_LY_NHA_DAT: 'phap-ly-nha-dat',
  AEO_GIA_NHA_PHO_THU_DUC_2026: 'gia-nha-pho-thu-duc-2026',
  AEO_BIET_THU_AQUA_CITY_GIA_BAO_NHIEU_2026: 'biet-thu-aqua-city-gia-bao-nhieu-2026',
  AEO_CAN_HO_VINHOMES_GRAND_PARK_GIA_BAO_NHIEU: 'can-ho-vinhomes-grand-park-gia-bao-nhieu',
  AEO_DAT_LONG_THANH_GIA_BAO_NHIEU_M2_2026: 'dat-long-thanh-gia-bao-nhieu-m2-2026',
  AEO_NHA_PHO_BINH_THANH_GIA_BAO_NHIEU: 'nha-pho-binh-thanh-gia-bao-nhieu',
  AEO_SO_HONG_VA_SO_DO_KHAC_NHAU_NHU_THE_NAO: 'so-hong-va-so-do-khac-nhau-nhu-the-nao',
  AEO_MUA_NHA_CHUA_CO_SO_DO_CO_AN_TOAN_KHONG: 'mua-nha-chua-co-so-do-co-an-toan-khong',
  AEO_PHAP_LY_AQUA_CITY_2026: 'phap-ly-aqua-city-2026',
  AEO_LUAT_DAT_DAI_2024_ANH_HUONG_GI_DEN_NGUOI: 'luat-dat-dai-2024-anh-huong-gi-den-nguoi-mua-nha',
  AEO_MUA_BDS_LONG_THANH_2026_CO_NEN_KHONG: 'mua-bds-long-thanh-2026-co-nen-khong',
  AEO_TOP_DU_AN_CAN_HO_TOT_NHAT_TPHCM_2026: 'top-du-an-can-ho-tot-nhat-tphcm-2026',
  AEO_SO_SANH_AQUA_CITY_VA_IZUMI_CITY_NEN_CHON: 'so-sanh-aqua-city-va-izumi-city-nen-chon-cai-nao',
  AEO_VAY_MUA_NHA_70_NGAN_HANG_NAO_TOT_NHAT_20: 'vay-mua-nha-70-ngan-hang-nao-tot-nhat-2026',
  AEO_LAI_SUAT_VAY_MUA_NHA_BIDV_VPBANK_TECHCOM: 'lai-suat-vay-mua-nha-bidv-vpbank-techcombank-2026',
  AEO_BDS_TP_THU_DUC_CON_TIEM_NANG_KHONG: 'bds-tp-thu-duc-con-tiem-nang-khong',
  AEO_KHU_VUC_NAO_TPHCM_DANG_TANG_GIA_2026: 'khu-vuc-nao-tphcm-dang-tang-gia-2026',
  AEO_GIA_DAT_BINH_DUONG_2026: 'gia-dat-binh-duong-2026',
  AEO_MUA_NHA_QUAN_9_CO_TOT_KHONG: 'mua-nha-quan-9-co-tot-khong',
  AEO_CAN_HO_STUDIO_VINHOMES_GRAND_PARK_CO_NEN: 'can-ho-studio-vinhomes-grand-park-co-nen-mua',
  AEO_DAT_DONG_NAI_KHU_VUC_NAO_TOT_NHAT_2026: 'dat-dong-nai-khu-vuc-nao-tot-nhat-2026',
  AEO_PHAP_LY_IZUMI_CITY_2026: 'phap-ly-izumi-city-2026',
  AEO_MANHATTAN_NOVALAND_CO_NEN_MUA_KHONG: 'manhattan-novaland-co-nen-mua-khong',
  AEO_THU_TUC_MUA_NHA_LAN_DAU_O_VIET_NAM: 'thu-tuc-mua-nha-lan-dau-o-viet-nam',
  AEO_KIEM_TRA_QUY_HOACH_TRUOC_KHI_MUA_NHA: 'kiem-tra-quy-hoach-truoc-khi-mua-nha',
  AEO_SANG_TEN_NHA_DAT_MAT_BAO_LAU: 'sang-ten-nha-dat-mat-bao-lau',
  AEO_TRANH_CHAP_DAT_DAI_GIAI_QUYET_NHU_THE_NA: 'tranh-chap-dat-dai-giai-quyet-nhu-the-nao',
  AEO_DAU_TU_BDS_CHO_THUE_O_TPHCM_2026: 'dau-tu-bds-cho-thue-o-tphcm-2026',
  AEO_YIELD_CHO_THUE_BDS_VIET_NAM_2026: 'yield-cho-thue-bds-viet-nam-2026',
  AEO_FLIPPING_BDS_LA_GI_CO_NEN_LAM_KHONG: 'flipping-bds-la-gi-co-nen-lam-khong',
  AEO_DAU_TU_BDS_VOI_VON_1_TY: 'dau-tu-bds-voi-von-1-ty',
  AEO_THUE_TNCN_BAN_NHA_DAT_2026: 'thue-tncn-ban-nha-dat-2026',
  AEO_TINH_KHA_NANG_VAY_NGAN_HANG_2026: 'tinh-kha-nang-vay-ngan-hang-2026',
  AEO_PHI_MOI_GIOI_MUA_BAN_NHA_DAT: 'phi-moi-gioi-mua-ban-nha-dat',
  AEO_BDS_QUAN_7_PHU_MY_HUNG_2026: 'bds-quan-7-phu-my-hung-2026',
  AEO_BDS_BINH_CHANH_VANH_DAI_2026: 'bds-binh-chanh-vanh-dai-2026',
  AEO_BDS_NHA_BE_2026: 'bds-nha-be-2026',
  AEO_CAN_HO_OFFICETEL_CO_NEN_MUA_KHONG: 'can-ho-officetel-co-nen-mua-khong',
  AEO_BDS_CAN_GIO_CO_TIEM_NANG_KHONG: 'bds-can-gio-co-tiem-nang-khong',
  AEO_BDS_THU_DUC_PHAN_KHU_NAO_TANG_GIA_MANH: 'bds-thu-duc-phan-khu-nao-tang-gia-manh',
  AEO_CHO_THUE_CAN_HO_VINHOMES_CO_LOI_KHONG: 'cho-thue-can-ho-vinhomes-co-loi-khong',
  AEO_MUA_NHA_O_XA_HAY_CAN_HO_TRUNG_TAM: 'mua-nha-o-xa-hay-can-ho-trung-tam',
  AEO_BDS_LONG_AN_KHU_VUC_NAO_TIEM_NANG: 'bds-long-an-khu-vuc-nao-tiem-nang',
  AEO_QUY_HOACH_VANH_DAI_3_TPHCM_ANH_HUONG_BDS: 'quy-hoach-vanh-dai-3-tphcm-anh-huong-bds',
  AEO_BDS_NGHI_DUONG_VIET_NAM_2026: 'bds-nghi-duong-viet-nam-2026',
  AEO_KIEN_TRUC_NHA_PHO_THU_DUC_LOAI_NAO_TOT: 'kien-truc-nha-pho-thu-duc-loai-nao-tot',
  AEO_THI_TRUONG_BDS_VIET_NAM_2026_TONG_QUAN: 'thi-truong-bds-viet-nam-2026-tong-quan',
  AEO_BDS_CONG_NGHIEP_VIET_NAM_2026: 'bds-cong-nghiep-viet-nam-2026',
  AEO_SO_SANH_MUA_VA_THUE_NHA_O_VIET_NAM: 'so-sanh-mua-va-thue-nha-o-viet-nam',
  AEO_QUA_TRINH_VAY_MUA_NHA_BAO_NHIEU_BUOC: 'qua-trinh-vay-mua-nha-bao-nhieu-buoc',
  AEO_LAM_THE_NAO_DE_CHON_MOI_GIOI_BDS_TOT: 'lam-the-nao-de-chon-moi-gioi-bds-tot',
    DU_AN: 'du-an',
    CHU_DAU_TU: 'chu-dau-tu',

    // Legal Pages
    PRIVACY: 'privacy-policy',
    TERMS: 'terms-of-service',
    COOKIES: 'cookie-settings',

    // Private Pages
    DASHBOARD: 'dashboard',
    LEADS: 'leads',
    CONTRACTS: 'contracts',
    INVENTORY: 'inventory',
    PROJECTS: 'projects',
    LISTING: 'listing', 
    LISTING_BDS: 'bds',
    FAVORITES: 'favorites',
    APPROVALS: 'approvals',
    CUSTOM_FIELDS: 'custom-fields',
    AUCTION: 'auction',
    UNIT_INVENTORY: 'unit-inventory',
    SYSTEM: 'system',
    ADMIN_USERS: 'admin-users',
    ROUTING_RULES: 'routing-rules',
    ENTERPRISE_SETTINGS: 'enterprise-settings',
    ADMIN_AI_COST: 'admin-ai-cost',
    BILLING: 'billing',
    CHECKOUT: 'checkout',
    INBOX: 'inbox',
    SEQUENCES: 'sequences',
    KNOWLEDGE: 'knowledge',
    SCORING_RULES: 'scoring-rules',
    REPORTS: 'reports',
    MARKETPLACE: 'marketplace-apps', // Internal App Store
    DATA_PLATFORM: 'data-platform',
    SECURITY: 'security',
    AI_GOVERNANCE: 'ai-governance',
    AI_EVALUATION: 'ai-evaluation',
    SEO_MANAGER: 'seo-manager',
    ERROR_MONITOR: 'error-monitor',
    PROFILE: 'profile',
    MOBILE_APP: 'mobile-app',
    RESET_PASSWORD: 'reset-password',
    VERIFY_EMAIL: 'verify-email',

    SCRAPER: 'scraper',
    CAMPAIGNS: 'campaigns',
    VENDOR_MANAGEMENT: 'vendor-management',

    // Task Management Module
    TASK_DASHBOARD: 'task-dashboard',
    TASK_KANBAN: 'task-kanban',
    TASKS: 'tasks',
    TASK_DETAIL: 'task',
    EMPLOYEES: 'employees',
    TASK_REPORTS: 'task-reports',

    // Commission engine v1
    COMMISSIONS: 'commissions',
  METHODOLOGY: 'methodology',
  PRESS_MEDIA: 'press-media',
  GLOSSARY: 'tu-dien-bat-dong-san',
  MARKET_REPORT: 'bao-cao-thi-truong',
} as const;

export const FULL_HEIGHT_PAGES = new Set([
    ROUTES.INBOX,
    ROUTES.LEADS,
    ROUTES.ADMIN_USERS,
    ROUTES.INVENTORY,
    ROUTES.CONTRACTS,
    ROUTES.FAVORITES,
    ROUTES.SYSTEM,
    ROUTES.TASKS,
    ROUTES.TASK_KANBAN,
    ROUTES.TASK_DETAIL,
]);

export type RouteKey = typeof ROUTES[keyof typeof ROUTES];
