export { SITE_URL, SITE_NAME, ORG_ID, WEBSITE_ID, LOGO_ID } from "./constants";
export { getOrganizationSchema } from "./organization";
export type { OrganizationSchema, GeoCoordinates, PostalAddress, ContactPoint, AggregateRating } from "./organization";
export { getWebsiteSchema } from "./website";
export type { WebsiteSchema } from "./website";
export { getRealEstateListingSchema } from "./realestate-listing";
export type { RealEstateListingSchema, RealEstateProject } from "./realestate-listing";
export { getFAQSchema, FAQ_HOMEPAGE } from "./faq";
export type { FAQSchema, FAQItem } from "./faq";
export { getBreadcrumbSchema } from "./breadcrumb";
export type { BreadcrumbSchema, BreadcrumbItem } from "./breadcrumb";
export { getFoundersSchema } from "./person";
export type { PersonSchema } from "./person";
export { getApartmentComplexSchema } from "./realestate-listing";
export type { ApartmentComplexInput } from "./realestate-listing";
